### ISSUE TITLE
add reattach() function to python

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#101]
Add a python function `pda = ak.reattach(name)` that will recreate the pdarray instance in python for an existing array in the server. This is useful for when the Jupyter kernel dies but the server stays running, in which case you want to re-populate your python namespace without redoing the chapel computations.

**Comment by mhmerrill** [comment]
@reuster986 I would like your thoughts on this...
 1. What if we would like to share the same arrays between Jupyter notebooks or python scripts?
 1. Is this needed for intermediate results of mostly to save on reading arrays again from the filesystem?
 1. Should we make the array immutable when it is registered? Some users have stated this desire to keep themselves from overwriting the array and having to load data again.
 1. How do we manage big memory leaks potentially created by this capability?
 1. Should we get rid of the server defined name for the array when it is registered?
 1. Should we provide a cleanup function to cleanup all arrays which are not registered?

My current thinking is an interface which looks like this:
```python3
pda1 = ak.ones(100)
# register a user defined name for the pdarray in the arkouda_server
# return a new pdarray with the "user_defined_name" in the pda.name field
# on the server side we could link the new name to the array
# and bump the shared reference count
pda2 = ak.register(pda1, "user_defined_name")
# list registered names from the server
name_list = ak.get_registered_names()
# attach the array under the user defined name to a new python pdarray object
pda3 = ak.attach("user_defined_name")
# attach all arrays registered in the server and put in a dictionary
# using the user defined names as the keys
pda_dict = ak.attach_all()
# remove the registration of the name
# should unregister reset the name back to a server assigned name
pda4 = ak.unregister("user_defined_name")
```

**Comment by reuster986** [comment]
@mhmerrill I have been thinking about this proposal, and I am somewhat ambivalent about taking this path. On the one hand, there is clear value in allowing users to save potentially lots of load time by re-using other people's data. On the other hand, this capability would break the "one server, one user" model, which is the cornerstone of our access control right now, i.e. the client's privileges are set to the server's privileges, because it is assumed that the client and server processes are run by the same user. Adding this feature to arkouda would, at the very least, require us to add a mechanism for the server to authenticate the client and for the server administrator to control access by various users. 

I don't think it would be too hard to do this, though. I would probably opt for a "one server, one team" model, in which an administrator whitelists the team members (e.g. using their ssh keys or a token stored in a file restricted to the team), and once the server authenticates a client as being a member of the team, they have free rein over the server. This is related to #60 , so I would want to resolve that before this one.

Having said that, I like the gist of this proposal. Specific responses:

1. This would be a useful feature.
2. I suspect the main use case for this feature would be to save everyone the trouble of loading in the data individually. Besides, any intermediate data that one wants to share with other users should probably also be persisted to disk, as a backup. So I see this mainly as caching and sharing disk reads (which is of course very valuable).
3. Yes, I think registered arrays should be immutable, mostly to protect users from getting into race conditions with each other. However, this feature could serve double duty to protect users from accidentally overwriting their own data, like you said.
4. I have no solution for this issue, except to point out that it places even more urgency on finding a way to estimate the amount of free memory an arkouda_server has left. I followed the discussion on the other thread that concluded there is no way to do this exactly, but even a rough estimate would be better than nothing.
5. I don't think we should get rid of the server-defined name, because there will be client objects that store that name, and it will be difficult to find and update all of them. Instead, I think we should keep both the server-defined and user-defined names in the symbol table, and just ensure that they point to the same GenSymEntry. That way, calling `st.lookup()` on either name works, so client objects can store either one.
6. I can't envision implementing this function in a multi-user environment without authentication (see above) and tracking ownership of arrays, because otherwise one user could delete everyone's unregeistered arrays. If we could track array ownership, then we could allow a user to only delete their own arrays.

One final thought: if we implement registered arrays, we would need to do reference-counting on them, so that unregistering an array would not trigger immediate deletion or removal of the name from the symbol table. Otherwise, a secondary user could lose access to their data in the middle of a computation.

**Comment by mhmerrill** [comment]
provided initial support in PR #290
