### ISSUE TITLE
Replace explicit `pn` (procedure name) variables with new Reflection feature(s)

### ISSUE THREAD

**Issue by bradcray** [mhmerrill/arkouda#114]
For your consideration:  While looking through Arkouda this month, I noticed the convention of using `pn` variables to store procedure names for use in generating messages and strings and the like.   In Chapel 1.20, there are new features in the `Reflection` module that support querying the filename, line number, routine (procedure or iterator) name, or module name of a given line of source, and I'm wondering whether the code could/should be rejiggered to make use of those features and reduce manual maintenance:

https://chapel-lang.org/docs/modules/standard/Reflection.html#Reflection.getRoutineName

**Comment by mhmerrill** [comment]
I have made a new branch to address this called `use-reflection-getroutinename`
