### ISSUE TITLE
Add test for negative values to argsort unit test

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#128]
Currently, UnitTestArgSortMsg.chpl only tests positive int64 and positive float64. We should add a case for mixed int64 and mixed float64.

**Comment by reuster986** [comment]
I think this was thoroughly resolved by the tests @ronawho added (I can't find the PR number right now)

**Comment by ronawho** [comment]
https://github.com/mhmerrill/arkouda/pull/207 added the standalone Chapel sorting test.
