### ISSUE TITLE
docs: Combine the outputs from chpldoc and pydoc?

### ISSUE THREAD

**Issue by BryantLam** [mhmerrill/arkouda#133]
Today, there are two documentation sources that get built: the server documentation with `chpldoc` and the Python frontend documentation with `sphinx-build`.

**Do we want to unify these multiple sources into one documentation source?**

After some experimentation, this is one approach to combine the outputs from chpldoc and pydoc into one documentation source:
1. Generate server documentation with `chpldoc --save-sphinx`
2. Copy the generated server doc files into a new pydoc/server directory
3. Build pydoc with the included pydoc/server directory

However, there are some problems that I ran into and foresee:

- For the Chapel maintainer that builds `chpl`, `chpldoc` gets built by initializing a virtualenv and installs very specific versions of packages from `$CHPL_HOME/third-party/chpl-venv/chpldoc-requirements.txt`
    - In order to reliably build pydoc with the chpldoc rst files, the current environment would likely need to be clobbered with the versions that chpldoc most reliably works with. E.g., Sphinx will get set to exactly v1.3.3
    - Or if we take the opposite approach and put Python doc source into the chpldoc-generated files and have chpldoc do the final build, then the chpldoc virtualenv has to include all dependencies ever needed by the included doc sources (e.g., numpy). Practically, this approach won't work if the Chapel installation isn't directly controlled by the user or the user duplicates the virtualenv (and remembers to synchronize it if the Chapel Project ever decides to repin the virtualenv package versions).
    - Both of these approaches are already a maintenance nightmare since new virtual environments need to be created or the user is forced to clobber their package versions with whatever is most compatible with chpldoc.

- More critically, the approach above does not scale if we ever introduce other frontends besides Python. Then, we'd have to figure out how to integrate three or more documentation sources, which quickly becomes a maintenance problem.

For these reasons, I don't think we should combine multiple documentation sources.
- An easier approach is to add links between the sources.
- The main disadvantage is that users won't have the ability to search between the frontend and backend documentations.

**Comment by mhmerrill** [comment]
I think we've addressed this so I am closing this issue.
