### ISSUE TITLE
Include a copy of arkouda documentation in the repo or not?

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#147]

**Comment by buddha314** [comment]
I usually prefer looking at the documents hosted on a page rather than in my source tree.

**Comment by hokiegeek2** [comment]
@mhmerrill I recommend closing this now that Arkouda is on [readthedocs](https://arkouda.readthedocs.io/en/latest/)

**Comment by hokiegeek2** [comment]
@mhmerrill Do you think we should close this? Seems like this issue is resolved.

**Comment by mhmerrill** [comment]
yep, closed
