### ISSUE TITLE
Sort performance thoughts

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#162]
Misc thoughts and suggestions for improving the performance of sort. 

The current sort implementation is limited by the speed of unorderedCopy. A majority of the time is spent putting elements into their correct position during the "calc new positions and permute" step, and if there are negative values reordering at the end.

Here's the microbenchmark I've been using to evaluate performance. It measures how fast raw unorderedCopy is and how fast sort for keys/ranks is. By default it operates on arrays that use 1/50 of memory and generates random 64-bit values. It has options to change the size, max numbers of bits used, and if only positive numbers should be used.

<details>

```chpl
use BlockDist;
use Memory;
use Random;
use Time;
use RadixSortLSD;
use UnorderedCopy;

config type elemType = int;
param elemSize = numBytes(elemType);

const totMem = here.physicalMemory(unit = MemUnits.Bytes);
config const memFraction = 50;
config const nElems = totMem / elemSize / memFraction * numLocales;

var t: Timer;
inline proc startDiag() {
  t.start();
}
inline proc endDiag(name) {
  t.stop();
  //writeln(name, " time : ", t.elapsed());
  const mbPerNode = (nElems * elemSize):real / (1024.0*1024.0) / numLocales:real;
  writef("%20s MB/s per node: %.2dr\n", name, mbPerNode/t.elapsed());
  t.clear();
}

config const positiveValues = false;
config const maxBits = numBits(elemType);
const modV = ((1 << maxBits) - 1): elemType;

proc main() {
  var D = newBlockDom({0..#nElems});
  var A, revA: [D] elemType;

  fillRandom(A, seed=314159265);
  if positiveValues then A = abs(A);
  if isIntegral(elemType) && maxBits < numBits(elemType) then A %= modV;

  startDiag();
  forall i in D do unorderedCopy(revA[nElems-1-i], A[i]);
  endDiag("unorderedCopy");

  startDiag();
  var B = radixSortLSD_keys(A);
  endDiag("radixSortLSD_keys");
  assert(isSorted(B));

  startDiag();
  var C = radixSortLSD_ranks(A);
  endDiag("radixSortLSD_ranks");
}
```

</details>

When sorting positive 16-bit values performance for radixSortLSD_keys  is pretty close to raw unorderedCopy:

```
./sort-perf -nl 16 --positiveValues=true --maxBits=16 --memFraction=50
       unorderedCopy MB/s per node: 481.49
   radixSortLSD_keys MB/s per node: 378.30
  radixSortLSD_ranks MB/s per node: 212.95
```

Sorting negative values is slower because the section to swap negative values is adding another unorderedCopy for each element.

```
./sort-perf -nl 16 --positiveValues=false --maxBits=16 --memFraction=50
       unorderedCopy MB/s per node: 483.58
   radixSortLSD_keys MB/s per node: 149.20
  radixSortLSD_ranks MB/s per node: 113.96
```

Sorting 32-bit values roughly halves performance since you need to go through the main loop twice now, which is expected.

Performance suggestions:
===

Overall, the performance is really close to the performance of just doing a raw unoderedCopy. The remaining gap is because sort is also counting digits, scanning, and computing buckets. There is some work that could be done to optimize those steps, but I don't think there is much room for improvement without switching to using bulk comm or having Chapel aggregate under the covers.

The standard library radix sort does use bulk comm, but it had other scalability issues. We're looking at those and have made some good progress so we should have some information to share about that soon.

Below are some concrete suggestions for improving the current implementation of radixSortLSD_keys/radixSortLSD_ranks

Negative values:
---

If you care about the performance of sorting negative numbers you could implement the last transform with bulk comm. That should be something like:
```chpl
// Copy negatives to the beginning
//  [(key, i) in zip(k1[firstNegative..], aD.low..aD.low+numNegatives-1 by negStride)] unorderedCopy(k0[i], key);
k0[{aD.low..aD.low+numNegatives-1}] = k1[{firstNegative..firstNegative+numNegatives-1}];
// Copy positives to the end
//  [(key, i) in zip(k1[..firstNegative-1], aD.low+numNegatives..)] unorderedCopy(k0[i], key);
k0[{aD.low+numNegatives..aD.high}] = k1[{aD.low..firstNegative-1}];
```

Which takes `./sort-perf -nl 16 --positiveValues=false --maxBits=16 --memFraction=50` from ~150 MB/s to ~325 MB/s, which is still below the ~380 MB/s for sorting non-negatives.

Alternatively, there are tricks to sort negatives and avoid the final transform. [Here](https://github.com/chapel-lang/chapel/blob/91b536840fd795d4b8d321dedddc474f9b96949c/modules/packages/Sort.chpl#L1449-L1454) is what Chapel's Radix Sort does for integers, and I believe there are similar tricks for reals.

radixSortLSD_ranks:
---

I think you know this already, but radixSortLSD_ranks is currently slower because the main loop has 2 unorderedCopy operations to move a tuple. That's the best you can do with 1.20, but on master you can implement this with a single unorderedCopy. If you want to experiment before the next official release, this should be a portable way to do that:

```chpl
use Reflection;
if canResolve("unorderedCopy", kr1[pos], kr0[i]) {
  unorderedCopy(kr1[pos], kr0[i]);
} else {
  unorderedCopy(kr1[pos][KEY],  kr0[i][KEY]);
  unorderedCopy(kr1[pos][RANK], kr0[i][RANK]);
}
```

`unorderedCopy()` on a 16-byte tuple is as fast as `unorderedCopy` on an 8-byte primitive, so that should bring radixSortLSD_ranks performance on par with radixSortLSD_keys.

**Comment by ronawho** [comment]
Aggregation:
===

I have some prototype aggregation work on a [branch](https://github.com/ronawho/arkouda/tree/aggregation) that has promising performance, especially for non-cray networks. On a Cray-XC, performance is ~2x better than unorderedCopy at 16 nodes and on par at 256 nodes. On an InfiniBand and Ethernet cluster, performance is hundreds of times faster. There is a high memory overhead since we have per-node destination buffers. The current usage is roughly `1MB * numLocales * here.maxTaskPar`. We should be able to lower the memory overhead and further improve scalability, but the initial numbers are promising. Below are scalability results in MB/s per node for radixSortLSD_keys (`./sort-perf --positiveValues=true --maxBits=16 --memFraction=50`). Results are on similar per-node hardware (36 core Broadwell CPUs and 128 GB RAM), so the main difference should be Aries vs. InfiniBand vs. Ethernet. `radixSortLSD_ranks` performance is within 20% of the keys numbers (and I think that gap can be closed some by tuning the buffer sizes)

The 2 node results for ibv/udp timed out after 30 minutes, so I gave up running them. We know that raw unorderedCopy only currently achieves ~2 MB/s per node for IBV compared to ~500 MB/s for Aries, so I'd expect <1 MB/s sorting for IBV and well below for udp if we let them run long enough.

Cray XC (Aries w/ ugni) :
---

| nodes | unordered | aggregated |
| ----- | --------- | ---------- |
|   1   | 925 MB/s  | 850 MB/s   |
|   2   | 605 MB/s  | 850 MB/s   |
|   4   | 485 MB/s  | 780 MB/s   |
|   8   | 485 MB/s  | 750 MB/s   |
|  16   | 385 MB/s  | 710 MB/s   |
|  32   | 370 MB/s  | 650 MB/s   |
|  64   | 365 MB/s  | 530 MB/s   |
| 128   | 365 MB/s  | 480 MB/s   |
| 256   | 355 MB/s  | 350 MB/s   |

Cray CS (FDR InfiniBand w/ gn-ibv-large):
---

| nodes | unordered | aggregated |
| ----- | --------- | ---------- |
|   1   | 935 MB/s  | 915 MB/s   |
|   2   | -         | 750 MB/s   |
|   4   | -         | 720 MB/s   |
|   8   | -         | 720 MB/s   |
|  16   | -         | 715 MB/s   |
|  32   | -         | 600 MB/s   |


Cray CS (Gigabit Ethernet w/ gn-udp-everything):
---

| nodes | unordered | aggregated |
| ----- | --------- | ---------- |
|   1   | 935 MB/s  | 915 MB/s   |
|   2   | -         |  82 MB/s   |
|   4   | -         |  22 Mb/s   |
|   8   | -         |  13 MB/s   |
|  16   | -         |   8 MB/s   |
|  32   | -         |   7 MB/s   |

Combined aggregation results:
---

| nodes | Aries      | IBV        | Ethernet   |
| ----- | ---------- | ---------- | ---------- |
|   2   | 850 MB/s   | 750 MB/s   |  82 MB/s   |
|   4   | 780 MB/s   | 720 MB/s   |  22 Mb/s   |
|   8   | 750 MB/s   | 720 MB/s   |  13 MB/s   |
|  16   | 710 MB/s   | 715 MB/s   |   8 MB/s   |
|  32   | 650 MB/s   | 600 MB/s   |   7 MB/s   | 



Example usage:
---

Here's what things look like from the user-perspective (note that there are distinct source and destination Aggregators):

```chpl
use Aggregation;

config type elemType = int;
config const nElems = 1_000_000;

var D = newBlockDom({0..nElems});
var A, revA: [D] elemType;

forall i in D with (var aggregator = new SrcAggregator(elemType)) {
  aggregator.copy(revA[i], A[nElems-i]);
}

forall i in D with (var aggregator = new DstAggregator(elemType)) {
  aggregator.copy(revA[nElems-i], A[i]);
}
```

Aggregators are flushed when they go out of scope or with manual `flush()` calls. Currently, the `SrcAggregator` requires the destination to be a local address. `DstAggregator` will work if the source is remote, but performance will suffer (since we're only aggregating in one direction)

**Comment by reuster986** [comment]
@ronawho this looks extremely promising! The sort is so critical to high-level arkouda operations that I think bringing infiniband performance in line with aries will really boost the viability of arkouda as a multi-platform tool. Do you see any downside to merging this branch in as it stands?

**Comment by reuster986** [comment]
@ronawho thanks so much for your effort on this, by the way!!!

**Comment by ronawho** [comment]
I was planning on doing some more tuning to see if we can reduce the amount of memory overhead and improve scalability a little more, but I'm hoping I could have something ready to merge within a week. 

Currently, each task uses ~1M*numLocales space. For a 512 node job with 40 cores per node that's ~20 GB of memory for aggregation buffers, which seemed excessive to me.

**Comment by reuster986** [comment]
Understood. I suppose that's not a trivial amount of memory, but worth the sacrifice if necessary, in my opinion. But if you can reduce that, go for it! 

FWIW, 1/50 of system memory is probably a pretty good estimate for the array sizes we're working with.

**Comment by mhmerrill** [comment]
There is probably a interplay/balance between bitsPerDigit and aggregation. I also think we should be able to reduce the memory footprint. I may be wrong but we can discuss it tomorrow in person.

**Comment by ronawho** [comment]
Just a heads up that my current plan is to get a PR open in the next few days that enables aggregation for non-Aries networks. This should provide immediate benefits to configurations that are currently unusably slow, while still allowing me time to tune the implementation before enabling it for Aries.

I expect I'll use smaller buffers than what I used for the initial experiments, so performance won't be as good as above, but it will get better as I have more time to tune.

**Comment by mhmerrill** [comment]
@ronawho I think we should also use the optimizations from the sort in the `IndexingMsg.chpl` module for gathers and scatters. I currently have the gathers and scatters in that module using `unorderedCopy()`.

**Comment by ronawho** [comment]
> I think we should also use the optimizations from the sort in the IndexingMsg.chpl module for gathers and scatters. I currently have the gathers and scatters in that module using unorderedCopy().

Captured in https://github.com/mhmerrill/arkouda/issues/210

**Comment by ronawho** [comment]
Optimized sorting negative values in https://github.com/mhmerrill/arkouda/pull/232

Enabled and optimized aggregation in https://github.com/mhmerrill/arkouda/pull/185 and https://github.com/mhmerrill/arkouda/pull/209
