### ISSUE TITLE
Convert MultiTypeSymbolTable.chpl from `shared` to `owned`

### ISSUE THREAD

**Issue by bradcray** [mhmerrill/arkouda#170]
I think that the current use of `shared` in `MultiTypeSymbolTable.chpl` is arguably overkill given the current usage patterns of its SymEntries and that the `owned` pattern probably makes more sense.  This issue's intention is to capture the notion of rewriting MultiTypeSymbolTable to use `owned` and `borrowed` rather than `shared` and `borrowed`.

**Comment by mhmerrill** [comment]
@bradcray originally the intention of using `shared` in the symbol table was that multiple symbols could reference the same `GenSymEntry`.
I should probably move a discussion of this into another place on the repo.
The way things turned out...
 1. using Python3 as the front-end language uses references exclusively, might not be true for other potential front-end languages like Julia or Ruby.
 2. arkouda_server has evolved into almost a single assignment interpreter (it's not quite because of scatter assignment and op= assignment), so we have mostly a DAG with self-loops.

Your thoughts?

**Comment by mhmerrill** [comment]
@reuster986 @bradcray @BryantLam We have also been discussing how to preserve symbol table entries across python-side problems. I have been thinking of putting in a hook `ak.register(pda,"name-ref")` which would associate a user defined name `"name-ref"` in the symbol table to the entry thus bumping the `shared` count and allowing the user to reconnect a python-side variable i.e. `pda = ak.reference("name-ref")` to a symbol table entry on the chapel-side. #101 suggests that this should be called `pda = ak.reattach("name-ref")`

**Comment by bradcray** [comment]
> originally the intention of using shared in the symbol table was that multiple symbols could reference the same GenSymEntry.

This pattern seems like it could be expressed by having the symboltable store the `owned` class objects and then have other references `borrowed` versions of that owned class.

> I have been thinking of putting in a hook ak.register(pda,"name-ref") which would associate a user defined name "name-ref" in the symbol table to the entry thus bumping the shared count

On the other hand, this type of pattern could be a good reason to keep it `shared`.

I should note that I'm not at all insistent that this change be made; I was just thinking it seemed plausible, but then in trying it, ran into some issues similar to the ones reported in https://github.com/chapel-lang/chapel/issues/14362 and https://github.com/chapel-lang/chapel/issues/14361 so filed this away as a potential rainy day activity.  If you guys are more confident we wouldn't want to go this way (or less confident that we would), I'd be fine with your closing it.

I also don't know that `shared` is hurting Arkouda in any significant way...  It generally has higher overhead than `owned`/`borrowed` due to the reference counting, but I think the frequency with which the reference count is touched, particularly relative to the likely much more expensive operations that occur on the arrays that a shared entry represents, means that it's probably not likely to be a high-order performance concern.

**Comment by mhmerrill** [comment]
I think with the discussion this issue was worth it. I am going to close it for now.
