### ISSUE TITLE
Translate setops into chapel server side operations

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#179]
Currently pdarray set operations like `ak.union1d()` consist of 5-12 seperate server operations.  Making the various set operations into single server side operations would provide significant speed improvement.

**Comment by mhmerrill** [comment]
> I am currently working on this issue, let me know if you have any concerns about this

@mcdobe100 I don't have any concerns. I do have a few ideas about this if you want to chat about it otherwise "have at it".

**Comment by mcdobe100** [comment]
@mhmerrill Yes, I would definitely be interested in chatting about this, when are you available? I currently have a branch `translate-setops` on my fork that has a proposed implementation for `union1d()` moved onto the server as `newUnion1d()` if you wanted to take a look at that.

**Comment by mhmerrill** [comment]
> @mcdobe100 asked: For getting the `overMemLimit` into my functions, do you have any recommendations for calculating out what they should be? Thanks.

I'll try to describe here what my process is for calulating a memory estimate.

1. remember, we want a high water mark for memory
1. look through the code and see what arrays get allocated
1. also look for extra data structures and calulate their memory foot print
1. remember all allocation in the symbol table get tracted and` overMemoryLimit` gets called for simple operations
1. more complex operations have to call `overMemoryLimit` with an estimate for the memory high watermark that will be hit during the computation

Lets take `argSort` for example:
https://github.com/mhmerrill/arkouda/blob/6bf11b62fbd0eec895e407559d752b86fd5da779/src/ArgSortMsg.chpl#L591-L597

1. the formula here says there are 4 intermediate arrays and the result allocated during the computation for the `radixSortLSD_ranks`
1. there are also the counts/bucket arrays allocated which depend on the task parallelism available and the number of locales.
1. Since we keep `itemsize` and `size` in the symboltable entry for the array passed in and we only sort` int64` and `float64` data I took a shortcut for the formula (my bad).

**Comment by mcdobe100** [comment]
```
overMemLimit(((6 + 1) * gEnt.size * gEnt.itemsize * gEnt2.size * gEnt2.itemsize));
```
 @mhmerrill Would this then be an acceptable `overMemLimit` for `union1d` then because of the 6 intermediate arrays allocated or would it instead be something like this
```
overMemLimit(((6 + 1) * gEnt.size * gEnt.itemsize * gEnt2.size * gEnt2.itemsize)
       + (6 * here.maxTaskPar * numLocales * 2**16 * 8));
```
because of the 3 calls to `uniqueSort`? (code shown below)

```
   proc union1d(a: [?aD] int, b: [aD] int) {
      var a1  = uniqueSort(a, false);
      var b1  = uniqueSort(b, false);
      var sizeA = a1.size;
      var sizeB = b1.size;

      var c = makeDistArray((sizeA + sizeB), int);

      c[{0..#sizeA}] = a;
      c[{sizeA..#sizeB}] = b;

      var ret = uniqueSort(c, false);
      
      return ret;
    }
```

**Comment by mhmerrill** [comment]
predicting memory usage is a little hard here because we are uniqueifying/deduping the input arrays into sets. the formula for worst case is something like... remember we want a high mark which isn't necessarrilary a sum... the result size is less than or equal to the size of `gEnt` added to the size of `gEnt2`... also I think I should add a memory usage estimator to the `radixSortLSD` module
```chapel
var gEnt_sortMem = radixSortLSD_memEst(gEnt.size, gEnt.itemsize);
var gEnt2_sortMem = radixSortLSD_memEst(gEnt2.size, gEnt2.itemsize);
union_maxMem = max(gEnt_sortMem, gEnt2_sortMem);
overMemLimit(union_maxMem);
```
this might not encompass all of the memory usage but it's closer

**Comment by ronawho** [comment]
Is this done with https://github.com/mhmerrill/arkouda/pull/392?

**Comment by mhmerrill** [comment]
> Is this done with #392?

Yes.
