### ISSUE TITLE
fix division and modulus operators to behave just like numpy with respect to divide by zero

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#184]
1. Currently the `operator_test.py` catches 18 errors where arkouda `pdarrays` don't behave like numpy `ndarrays`.
1. These all seem to involve `//`,`/`, and `%` operators and dividing by zero. 
1. Arkouda currently throws a runtime exception on divide by zero which numpy doesn't seem to do.
1. In numpy it appears that you can control this behavior with `numpy.seterr(divide='ignore')` which seems to be the default (default return is `inf`).

**Comment by mhmerrill** [comment]
@bradcray @mppf @ronawho I would like to get the Chapel code to behave like numpy in the divide-by-zero case. I think the default for numpy is to return `inf` (infinite).

**Comment by mhmerrill** [comment]
truediv
np.int64(0) / np.int64(0) = nan
np.int64(1) / np.int64(0) = inf
floordiv
np.int64(0) // np.int64(0) = 0
np.int64(1) // np.int64(0) = 0

**Comment by bradcray** [comment]
@mhmerrill: For the truediv cases, I think what you're seeing is consistent with (my understanding) of IEEE floating point given that Python defines division between two integers as being a float. In contrast, Chapel preserves the integer nature, as in C and as discussed a bit on https://github.com/chapel-lang/chapel/issues/14306

[This TIO session](https://tio.run/##dY5BCsIwEEX3OcXQldk4ybbBw4SS2oHQkbEo5PKRVMQk1uW8/wbetPhbiDlPvM50hYcXSAQXME7VSAo6t5CLZ1tUPFs89RTaQlxPg0EzDtopxA9KhIm0A0CExcftrr7LKMHHfVaNvvMOSn1L9yTtrusk@5PEf5P4KImPkrhL4i6J30k5vwA) suggests to me that for cases involving floats in Chapel (including casting an int argument to real), the results are the same as for truediv.  To make Arkouda and NumPy / Python behave similarly in this case, would it be sufficient to have the translation of the operation to Chapel introduce the cast to real for int, int division?

I'm less familiar with floordiv and would need to dig into it further to offer an opinion.

**Comment by mhmerrill** [comment]
PR #187 fixes this issue ;-)
