### ISSUE TITLE
remove NotImplemented

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#201]
A couple places (e.g.  [here](https://github.com/mhmerrill/arkouda/blob/e1df53466f5948726103e112f9a77392f6091d53/arkouda/pdarrayclass.py#L111)) in the python client return `NotImplemented`, which is a python pass-through that allows implementers to integrate new classes with existing python classes. However, we should not be using it, because nothing else knows about the `pdarray` class. Instead, we should raise a `ValueError` like numpy.

**Comment by mhmerrill** [comment]
fixed with PR #203
