### ISSUE TITLE
use aggregation for gather and scatter indexing patterns

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#210]
modify `IndexingMsg.chpl` to use `CommAggregation.chpl` module in addition to `unorderedCopy`

**Comment by mhmerrill** [comment]
https://github.com/mhmerrill/arkouda/blob/e314d80b463b2dd0e19bb9964c83d1b0f896567e/src/IndexingMsg.chpl#L72-L80

**Comment by mhmerrill** [comment]
pda[int64] gather indexing with an int64 index-vector(called `iv` in the code)
https://github.com/mhmerrill/arkouda/blob/e314d80b463b2dd0e19bb9964c83d1b0f896567e/src/IndexingMsg.chpl#L114-L129
pda[bool] compression indexing with a bool index-vector(called `truth` in the code)
https://github.com/mhmerrill/arkouda/blob/e314d80b463b2dd0e19bb9964c83d1b0f896567e/src/IndexingMsg.chpl#L132-L146

**Comment by mhmerrill** [comment]
pda[[int64]] = val scatter indexing using a [int64] index-vector
https://github.com/mhmerrill/arkouda/blob/e314d80b463b2dd0e19bb9964c83d1b0f896567e/src/IndexingMsg.chpl#L263-L280
pda[[bool]] = val expansion indexing using a [bool] index-vector
https://github.com/mhmerrill/arkouda/blob/e314d80b463b2dd0e19bb9964c83d1b0f896567e/src/IndexingMsg.chpl#L283-L297

**Comment by mhmerrill** [comment]
pda1[[int64] = pda2 scatter indexing using a [int64] index-vector
https://github.com/mhmerrill/arkouda/blob/e314d80b463b2dd0e19bb9964c83d1b0f896567e/src/IndexingMsg.chpl#L342-L358
pda1[[bool]] = pda2 expansion indexing using a [bool] index-vector
https://github.com/mhmerrill/arkouda/blob/e314d80b463b2dd0e19bb9964c83d1b0f896567e/src/IndexingMsg.chpl#L361-L377

**Comment by ronawho** [comment]
@mhmerrill I have a start on this at https://github.com/mhmerrill/arkouda/compare/master...ronawho:aggregate-IndexingMsg

With this `argsort.py --scale-by-locales`, `gather.py`, and `scatter.py` benchmarks all finish in under 60s on InfiniBand  (I gave up running them after 15 minutes before)

I need to aggregate the bool cases and tune for ugni, but that should be pretty straightforward.

**Comment by mhmerrill** [comment]
@ronawho I noticed a slight typo in line 78 (I can't link it for some reason) you are using `a.a` instead of `aa` which you should be using.
> @mhmerrill I have a start on this at [master...ronawho:aggregate-IndexingMsg](https://github.com/mhmerrill/arkouda/compare/master...ronawho:aggregate-IndexingMsg)
> 
> With this `argsort.py --scale-by-locales`, `gather.py`, and `scatter.py` benchmarks all finish in under 60s on InfiniBand (I gave up running them after 15 minutes before)
> 
> I need to aggregate the bool cases and tune for ugni, but that should be pretty straightforward.

**Comment by ronawho** [comment]
Ah, good catch -- I must have started with the out-of-date commented out line.
