### ISSUE TITLE
Convert remaining uses of unorderedCopy to aggregation

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#222]
Aggregation has significantly better performance on non-cray networks. We should remove the remaining uses of unorderedCopy (and look for plain assignments that could be aggregated.)

**Comment by mhmerrill** [comment]
@ronawho these occurrences on ArgSortMsg.chpl should be replaced.
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/ArgSortMsg.chpl#L376
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/ArgSortMsg.chpl#L384
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/ArgSortMsg.chpl#L392
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/ArgSortMsg.chpl#L400-L401
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/ArgSortMsg.chpl#L407

**Comment by mhmerrill** [comment]
these occurrences in FindSegments.chpl should be converted to aggregation.
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/FindSegmentsMsg.chpl#L96
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/FindSegmentsMsg.chpl#L142
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/FindSegmentsMsg.chpl#L148

**Comment by mhmerrill** [comment]
there is a question I have about FindSegments.chpl, would unorderedCopy/Aggregation help with the two commented-out lines? Scattering a `true` into a block distributed bool array.
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/FindSegmentsMsg.chpl#L195
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/FindSegmentsMsg.chpl#L211

**Comment by mhmerrill** [comment]
@reuster986 does this occurrence have to do with string IO?

GenSymIO.chpl occurrence:
https://github.com/mhmerrill/arkouda/blob/9712f3608ba20b7d69f7f1ab51927d3413f01d3b/src/GenSymIO.chpl#L310

**Comment by reuster986** [comment]
@mhmerrill yes, this occurence and the function containing it are necessary because segmented strings are stored in HDF5 as an array of offsets and an array of bytes, but the offsets are not absolute offsets, they are offsets relative to the start of the file. To form an array of strings from multiple files, it is necessary to translate those per-file relative offsets into absolute offsets for the array.

**Comment by mhmerrill** [comment]
looks like we should also fix the ones in:
SegStringSort.chpl
SegmentedArray.chpl
Unique.chpl

**Comment by mhmerrill** [comment]
I am going to close this issue because I think we addressed it with #235

**Comment by ronawho** [comment]
There's a couple places that remain (marked TODO in the code) in https://github.com/mhmerrill/arkouda/pull/235

**Comment by ronawho** [comment]
The last remaining uses of unorderedCopy are in `findSegmentsMsg()` and `peel()`/`stick()`. I think peel and stick are labeled as experimental so might not be a huge deal, but I'm not sure how much `findSegmentsMsg()` is used.

**Comment by reuster986** [comment]
Aha! I was actually about to open an issue on improving performance of `findSegmentsMsg()`. It's pretty important -- it's the second half of `GroupBy`, after the `coargsort` -- and I thought it was running a bit slow.

**Comment by ronawho** [comment]
The only remaining uses of `unorderedCopy` are in `peel()`/`stick()` which are labeled as experimental, so I'd be fine closing this issue at this point.
