### ISSUE TITLE
Add tests for operator bugs that users discovered

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#227]
* `scalar < pdarray` triggers iteration
* `pdarray and pdarray` does something wacky, should raise `TypeError`, e.g. inside a `pdarray.__bool__()` method.
* `ak.zeros([1, 2, 3, 4], dtype=int64)` crashes the server:

```
uncaught IllegalArgumentError: bad cast from string '[1,' to int(64)
  src/MsgProcessing.chpl:45: thrown here
```

**Comment by mhmerrill** [comment]
looks like we need to put in a
```python
pdarray.__bool__()
```
to emulate NumPy
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by mhmerrill** [comment]
PR #228 addresses my comment about the Python ValueError.
