### ISSUE TITLE
fix pip3 install arkouda for installs with zmq and hdf5 already installed in non-standard places

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#230]
fix pip3 install arkouda for installs with zmq and hdf5 already installed in non-standard places.

I am having trouble with `pip3 install -e .` on our IB cluster where we have libraries installed not installed by `pip3`

Currently, we need to pip re-install when we rev the version number which we should also fix and detangle these issues.

@reuster986 @Spartee you guys should look at this.

**Comment by reuster986** [comment]
@mhmerrill this is a pretty thorny issue, and I'm not sure exactly what to do. I propose that we support two official ways of installing arkouda:

* User mode
  * For non-developers who just want server and client to install with one command
  * Syntax: `pip install arkouda`
  * Status: almost done
    * Works on mac
    * On linux, fails to build `arkouda_server` because it can't find zmq or hdf5, even with `LD_LIBRARY_PATH` set. I propose we modify `installers.py` to copy `LD_LIBRARY_PATH` to `Makefile.paths` and check that it can build a trivial Chapel program linked against zmq and hdf5. I am willing to do this, if there are no objections.
* Developer mode
  * For developers or users who need to decouple the building of `arkouda_server` from the installation of the `arkouda` python package.
  * Current method: `make`, followed by `pip install -e /path/to/arkouda/repo`
  * Status: needs work
    * @mhmerrill what specific error is this command giving with respect to zmq and hdf5? I can't reproduce on sherlock because I can't re-install over your copy.
    * @mhmerrill note that even if there is a custom build of zmq for linking into the `arkouda_server`, the `arkouda` python package still needs the `zmq` python package, so `pip` still has to install `zmq`.
    * As @mhmerrill points out, the current code gets the `__version__` number from when the python package was built, i.e. when `pip install -e` was run. This is fine for user mode but wrong for development mode, because the `__version__` should be set at import-time. I think this can be done by reading the `VERSION` file on import, as long as we can force setuptools to always include this file in the distribution, so that it also works with user mode. @Spartee does it already do this, or do you know how to make it do so? I can't test it, because I can't complete a normal `pip install arkouda` to look at the result.

**Comment by mhmerrill** [comment]
@ronawho proposed a fix for me which works for me.
```bash
make -j install-deps
pip3 install -e . --user
make
```

**Comment by reuster986** [comment]
I believe #233 fixes this.
