### ISSUE TITLE
bool concatenate bug

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#236]
These three lines produce the segfault when run on 2 or 32 locales on our XC (arkouda v 2019.12.10):
```python
import arkouda as ak
ak.connect()
b = ak.zeros(6*10**8 + 1, dtype=ak.bool)
c = ak.ones(6*10**8 + 1, dtype=ak.bool)
d = ak.concatenate((b, c))
[segfault]
```
There is no segfault if you remove the "+ 1"s in the array sizes.
The int and real arrays don't segfault and it's the same code just with different types.

**Comment by mhmerrill** [comment]
it appears to be a bug with indexing BlockDist bool arrays:
https://github.com/mhmerrill/arkouda/blob/a2e6288092512af808f7e3fcfd144d1d6de74b70/src/ConcatenateMsg.chpl#L82-L98

**Comment by mhmerrill** [comment]
I tried to reproduce it on our IB cluster and it didn't segfault.

**Comment by bradcray** [comment]
I suspect that whatever the bug is, it isn't specific to booleans, so much as it's only getting revealed in the boolean case because it's not a 64-bit type.

**Comment by e-kayrakli** [comment]
The PR github auto-ref'd above should fix the issue (https://github.com/chapel-lang/chapel/pull/14652)

**Comment by ronawho** [comment]
This is a bug in the ugni comm layer for code that handles GETs where the source, target, or length isn't 4-byte aligned (which is required by the Aries NIC.) This works for ints/reals since the size ends up being 4-byte aligned, and it works for similar reasons without the `+1`

Since this is a runtime change, I don't think we have any great options for getting you a fix with the 1.20 release. I think the simplest workaround for now is to implement `ak.bool` with `bool(32)`.

**Comment by bradcray** [comment]
@mhmerrill: If you'd like us to make a 1.20.x bug fix release for this, let us know.  If you're in a scenario where you can rebuild 1.20 from source, we could also supply a patch to apply to incorporate the fix.

**Comment by mhmerrill** [comment]
@BryantLam @bradcray we are currently working around this bug on the Cray XC in the python code. I would like @BryantLam to weigh-in on the difficulty of applying the patch to the Cray XC build of Chapel. i believe that this bug only effects the Cray XC (based on ugni comm layer) install of Chapel.

**Comment by bradcray** [comment]
That's correct that it's only a bug/fix for XC (and XE) due to its ugni-based nature.

-Brad

**Comment by bradcray** [comment]
(As mentioned [above](https://github.com/mhmerrill/arkouda/issues/236#issuecomment-566225028), we could also roll out a bug fix release for this if that would be helpful).

**Comment by mhmerrill** [comment]
This bug has also showed up now with our Arkouda Strings support.

**Comment by ronawho** [comment]
Anything you need from us on this one yet?

**Comment by reuster986** [comment]
Sorry, forgot to test this one earlier. I just ran the reproducer and got the correct output, so I'll close.
