### ISSUE TITLE
checks.py can fail because of floating point precision

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#239]
On some multi-locale systems `checks.py` (specifically `check_linspace`) fails for me because of slight floating point differences.

Instead of using array equality checks, something like [`numpy.allclose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html)/[`numpy.isclose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isclose.html) might be more appropriate.

**Comment by mhmerrill** [comment]
ok, i'll fix the linspace test.
