### ISSUE TITLE
Aggregation with loop-private variables?

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#250]
@ronawho I'm not sure if this is a bug to fix or just a pitfall that I need to learn how to avaoid, but aggregators don't seem to play well with variables created inside a `forall`. For example, this code does not correctly copy `A` to `B`:

```chapel
var D: domain(1) dmapped Block(boundingBox={0..#N}) = {0..#N};
var A: [D] int = [i in D] i;
var B: [D] int;
forall (b, i) in zip(B, D) with (var agg = new SrcAggregator(int)) {
    var a = A[i];
    agg.copy(b, a);
}
```

Each task's chunk of `B` ends up filled with a constant value (the last value in that task's chunk of `A`). 

The `SegString` gather code stumbles over this same behavior [here](https://github.com/mhmerrill/arkouda/blob/d9ec5191ce93cade222de8ee3ee438f6bc4ecfb4/src/SegmentedArray.chpl#L129-L137). I'll be submitting a PR with a workaround shortly, but I wanted to ask you if there's a better way to handle this.

**Comment by ronawho** [comment]
The `SrcAggregator` aggregates the source and destination addresses. In this case you're aggregating the address of the variable `a`, not the address of `A[i]`. When the aggregator is flushed it copies the current value of `a` to all the destination addresses.

I think what you'd want here is `agg.copy(b, A[i]);` or `ref a = A[i]; agg.copy(b, a);`

Not that `var a = A[i]` is effectively `var a = GET(A[i]);` so it's not actually aggregating the comm anyways.

**Comment by reuster986** [comment]
I'm going to close this because there is nothing to be done except learn from the experience.
