### ISSUE TITLE
aggregation bug

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#258]
This should be a DstAggregator, not a SrcAggregator, I think:

https://github.com/mhmerrill/arkouda/blob/844d2d33e7e30881469b16725dd50c856d884848/src/ReductionMsg.chpl#L1011

**Comment by mhmerrill** [comment]
@ronawho could you comment on this?

**Comment by ronawho** [comment]
Whoops. Yeah the destination is remote, so that should be a DstAggregator. I opened https://github.com/mhmerrill/arkouda/issues/258 for this.
