### ISSUE TITLE
Server crashes on creating *large* arrays

### ISSUE THREAD

**Issue by gnat79** [mhmerrill/arkouda#279]
There is a (reasonable) upper bound on how large an array arkouda can handle, and exceeding that size causes a crash instead of passing an error to python.  For example,

        x = ak.arange(0, 10**12)

The message returned is something like:
src/MultiTypeSymEntry.chpl:81: error: Out of memory allocating "array elements"

This is with server version 2019.12.12 on a small number of nodes. So it's **clearly** not a reasonable expectation for how much memory that operation requires.

**Comment by mhmerrill** [comment]
FYI, This has already been addressed... @gnat79 use the `--memTrack=true` flag on the server run line, maybe @reuster986 should enable it by default in out launch script.

**Comment by gnat79** [comment]
Okay, thanks!
