### ISSUE TITLE
server crashes on ak.info call if the server symbol table is empty

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#280]
server crashes on `print(ak.info(ak.AllSymbols))` if the symbol table in the server is empty. to make this happen start a server, connect the client then immediately execute the command above.

**Comment by mhmerrill** [comment]
i think this might be a chapel bug. The server is crashing in these lines
https://github.com/mhmerrill/arkouda/blob/6d3e760d7ef9c4f83c5e8d73e4dfb03235647625/src/MultiTypeSymbolTable.chpl#L194-L200

seems like the `for` loop on line 195 should not run if the domain is empty.

**Comment by bradcray** [comment]
I'm trying to reproduce this, but haven't been successful yet (though I am seeing a different behavior that's surprising to me — an uncaught exception leading to an "out of memory" style error).

I'm using Chapel 1.20 on a Mac, Arkouda at `SHA 6d3e760d7ef9c4f83c5e8d73e4dfb03235647625` and the following Python program:

```chapel
#!/usr/bin/env python3                                                         

import sys

import arkouda as ak

ak.verbose=False
if len(sys.argv) > 1:
    ak.connect(server=sys.argv[1], port=sys.argv[2])
else:
    ak.connect()

print(ak.info(ak.AllSymbols))
```

The output I get is:

```
arkouda server version = 2020.02.04
memory tracking = false
server listening on C02QP2LLG8WM:5555
reqMsg: connect
repMsg:connected to arkouda server tcp://*:5555
<<< connect took 0.00011999999999989797 sec
reqMsg: getconfig
repMsg:{"arkoudaVersion":"2020.02.04", "ZMQVersion":"4.3.2", "HDF5Version":"1.10.5", "serverHostname":"C02QP2LLG8WM", "ServerPort":5555, "numLocales":1, "numPUs":4, "maxTaskPar":4, "physicalMemory":17179869184, "distributionType":"BlockDom(1,int(64),false,unmanaged DefaultDist)", "LocaleConfigs":[{"id":0, "name":"C02QP2LLG8WM", "numPUs":4, "maxTaskPar":4, "physicalMemory":17179869184}]}
<<< getconfig took 0.00055699999999969663 sec
reqMsg: info __AllSymbols__
<<< info took 3.7999999999982492e-05 sec
(null):371: error: Out of memory allocating "io buffer or bytes"
```

which makes it look as though the "info" command is completing successfully.  Compiling with debugging on and running within lldb, the out-of-memory message is coming from the main socket.recv() call on line 63:

```chapel
        var reqMsgRaw = socket.recv(bytes);
```

adding debug writeln()s within the `info()` routine that you point to above Mike, I'm finding that the call is being made, that tD is empty, and that the loop isn't executing, as expected (in that a writeln() within the loop isn't triggering:

```
In info(), name is __AllSymbols__
tD is: {}
<<< info took 5.4999999999694182e-05 sec
```

Does the uncaught exception / out-of-memory error make sense to you?  Or might the difference in behaviors we're seeing suggest that there's some sort of memory corruption going on that's manifesting in different ways for us?

**Comment by bradcray** [comment]
I'm seeing the same OOM error on my Mac when using Chapel master.

If I go back to Arkouda SHA f273852 things seem to work OK.  If I go to SHA db73b4b, they break again.  This suggests PR #260 is at fault.

@e-kayrakli how soon would you be able to take a look?  (as noted above, I wonder whether memory corruption is at fault, but haven't had a chance to look into that at all yet).

**Comment by e-kayrakli** [comment]
Reading the issue, I don't have an immediate reaction that I am confident enough to speculate. I'll have more to say on Monday.
