### ISSUE TITLE
Eliminate domain slices

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#286]
@ronawho recently [pointed out](https://github.com/mhmerrill/arkouda/issues/266#issuecomment-585259473) that the domain slicing idiom `a[{i..j}]` is really bad because it forces everything onto locale 0. We should elimnate this pattern from the arkouda codebase. Hopefully we can find everything by searching for `[{` in the code.

---

The length calculation being slow is a bit subtle, so I wanted to call out the reason. The problem is that in SipHashSpeedTest, the calculation uses local domains: https://github.com/mhmerrill/arkouda/blob/5e1581a48e7a1eadb85059d437c276b51e2e5b2c/test/SipHashSpeedTest.chpl#L38-L40

Since https://github.com/chapel-lang/chapel/pull/12931, slice expressions are governed by the slicing domain. Since the domains used to slice are local, your length calculation is local, which means everything is running on locale 0 using GETs/PUTs.

I believe the actual length calculation in arkouda is slicing with ranges:
https://github.com/mhmerrill/arkouda/blob/5e1581a48e7a1eadb85059d437c276b51e2e5b2c/src/SegmentedArray.chpl#L337-L348

Today, this gives you distributed slices, but I'm not sure that will be true longer term. @bradcray will know more about that though. 

---

Here are a couple variations for computing the length (not positive they're all correct, but I think they are):

```chpl
use RandArray;
use Time;

config const NINPUTS = 100_000;
config const INPUTSIZE = 8;

enum operation {loop, domainSlice, rangeSlice, interior};

const logMean:real = log(INPUTSIZE:real)/2;
const logStd:real = sqrt(2*logMean);
var (segs, vals) = newRandStringsLogNormalLength(NINPUTS, logMean, logStd);
const D = segs.domain;
var lengths: [D] int;

for op in operation {
  resetCommDiagnostics(); startCommDiagnostics();
  var t = new Timer(); t.start();

  if op == operation.loop {
    forall (l, s, i) in zip(lengths, segs, D) {
      if i == D.high then l = vals.size - s;
                     else l = segs[i+1] - s;
    }
  } else if op == operation.domainSlice {
    lengths[{D.low..D.high-1}] = segs[{D.low+1..D.high}] - segs[{D.low..D.high-1}];
    lengths[D.high] = vals.size - segs[D.high];
  } else if op == operation.rangeSlice {
    lengths[D.low..D.high-1] = segs[D.low+1..D.high] - segs[D.low..D.high-1];
    lengths[D.high] = vals.size - segs[D.high];
  } else if op == operation.interior {
    const s = D.size-1;
    lengths[D.interior(-s)] = segs[D.interior(s)] - segs[D.interior(-s)];
    lengths[D.high] = vals.size - segs[D.high];
  }

  t.stop();
  stopCommDiagnostics();

  writef("%-12s: %.3dr first-%s last-%s\n", op:string, t.elapsed(), getCommDiagnostics()[0]:string, getCommDiagnostics()[numLocales-1]:string);
}
```

Run on 16 nodes of an InfiniBand cluster:

```
$ ./SipHashSpeedTest -nl 16
loop        : 0.001 first-(get = 8, execute_on_nb = 15) last-(execute_on_fast = 1)
domainSlice : 1.263 first-(get = 187703, put = 93750, execute_on = 12) last-(<no communication>)
rangeSlice  : 0.010 first-(get = 2, put = 1, execute_on = 18, execute_on_nb = 105) last-(get = 177, put = 3, execute_on_fast = 7)
interior    : 0.009 first-(get = 2, put = 1, execute_on = 24, execute_on_nb = 105) last-(get = 177, put = 3, execute_on_fast = 7)
```

The local domain slice is really bad since everything is running on locale 0. The others are all good. The loop is fastest since there's no distributed domain creation, but I would expect the performance difference to be negligible compared to the time to hash. I'd probably avoid the rangeSlice since I believe we expect that to behave like a local domain the future.

_Originally posted by @ronawho in https://github.com/mhmerrill/arkouda/issues/266#issuecomment-585259473_

**Comment by ronawho** [comment]
@bradcray is the expert here, and will likely have more to say.

For the original SipHash context, you are operating on all of the elements of the distributed array, but part of the motivation for chapel-lang/chapel#12931 is when you're only operating on a subset of the elements. For instance something like: `arr[{D.low..D.low+10}] = arr[{D.high-10..D.high}];` will be much faster than creating new distributed domains for those slices.

https://chapel-lang.org/releaseNotes/1.20/03-arrays.pdf ("Array Slice Improvements" section) has some additional context/motivation.

**Comment by bradcray** [comment]
Sorry for the slow reply.  I don't have much to add other than what @ronawho said above, but will maybe restate one thing for emphasis:

For the time being, my guidance as to when to use `A[lo..hi]` vs. `A[{lo..hi}]` would depend on whether `lo..hi` spans most locales (in which case I'd use the former) or just a few (in which case I'd use the latter; I the cases in Arkouda that originally motivated using this notation fell into this case, which is probably what led you down this path).

FWIW, I'm continually frustrated that the slicing improvements I was working on in the 1.20 timeframe had to get put on pause for the Chapel 2.0 effort.  I do hope that I, or someone else, will be able to take up this effort back up again soon.

**Comment by reuster986** [comment]
I think I converted all the cases of domain slicing in #309
