### ISSUE TITLE
Ramp up automated testing

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#313]
Especially as Chapel 1.21 gets closer, I find myself wanting to be able to run more of the tests to ensure that things are working as expected. I think there's a couple classes of tests that would be really beneficial to automate (even if some of them can't be run as part of CI.) 

Related to https://github.com/mhmerrill/arkouda/issues/217, https://github.com/mhmerrill/arkouda/issues/214, https://github.com/mhmerrill/arkouda/issues/90, https://github.com/mhmerrill/arkouda/issues/89, https://github.com/mhmerrill/arkouda/issues/41, https://github.com/mhmerrill/arkouda/issues/319

I think there's a couple classes of tests that are important:

basic unit tests:
---
Basic tests that we could run as part of CI like the python tests in `tests/` and chapel tests in `test/UnitTest*`.

basic performance tests:
---
I'm thinking mostly of arkouda microbenchmarks like the ones in the `benchmarks/` dir. I don't think we can do performance testing as part of CI, but we should run them in a correctness mode, and I'm working on setting up nightly performance testing on single-node, a Cray-CS, and a Cray-XC. I'm most interested in arkouda tests here, but some of the `test/*SpeedTest.chpl` standalone chapel test have been really useful when doing performance turning so we should probably run them in a correctness mode as part of CI testing to make sure they still work.

large scale arkouda tests:
---
More complex tests that create and operate on large datasets. I'm thinking along the lines of stress tests that will use a large fraction of memory. I expect we can run these with a much smaller problem size for CI, but large scale testing could be tied into nightly performance testing.

example workflows on "real" data:
---
I'm imagining something that takes a large sample/well-known public dataset and runs a sample workflow. 

I'm happy to help setup the infrastructure, especially for the first 3, but I will likely need help converting tests to whatever infrastructure we decide on.

**Comment by ronawho** [comment]
I believe all the infrastructure is now in place for ramping up CI testing. We have the ability to:
 - run Chapel unit tests (currently uses `start_test`) -- infrastructure added in https://github.com/mhmerrill/arkouda/pull/312
 - run Python unit tests (uses `runClient`) -- infrastructure added in https://github.com/mhmerrill/arkouda/pull/317
 - run benchmarks in correctness mode (uses `run_benchmarks`) -- infrastructure added in https://github.com/mhmerrill/arkouda/pull/320

---

@mhmerrill and @reuster986 my goal was just to set up the infrastructure to enable Python and Chapel unit testing. I don't think I'll be very helpful for enabling the other chapel and python unit tests (I'm not sure what the correct output/result is for many tests.) I plan on leaving that for you, but let me know if I can help. 

Misc things that I noticed looking at some of the Chapel unit  tests: 
 - You could make them all `prototype module`s to avoid needing to explicitly catch errors
 - It might be nice to switch from using BlockDist to `makeDistDom`/`makeDistDomArr`
 - You probably want to disable timers by default (or add a .execopts file to disable them) and maybe use `%.2dr` instead of `%t` to avoid exponential notation for timers. 
 - Some cases use strings to select different modes and that might be a little cleaner using enums. e.g. UnitTestSipHash `"fixed"/"variable"` LENGTH to an enum

**Comment by reuster986** [comment]
Cool, @ronawho !

I mentioned just now on #337 that @hokiegeek2 is reorganizing the python-side arkouda test suite into the workflow-like tests you mention above and true unit tests that aim for good code coverage. I think the plan is to have the workflow-like tests run under CI and the more thorough unit tests be available for developers working on specific functional areas. Also, I don't think @hokiegeek2 is planning to change anything about performance testing or the Chapel-side tests, at least for now (please correct me if I'm wrong, John).

**Comment by hokiegeek2** [comment]
Hey @reuster986 yep, not changing any of the Chapel tests. Adding pytest and pytest-env dependencies to implement a python test harness that can integrate into a CI/CD workflow as well as be executed by a developer. Also, the Python unit tests can be run in debugger mode. Finally, there is a concept of executing the unit tests in full-stack mode (local arkouda server setup at beginning of a Python test case and torn down at the end) or client stack mode where the Python unit tests execute against an arkouda server that is managed externally. The client stack mode enables benchmarking tests from the same set of Python test cases.

**Comment by ronawho** [comment]
FYI with https://github.com/chapel-lang/chapel/pull/15651 we run the python unit testing in the same configs that run performance testing, so we have testing that checks Arkouda master against the chapel 1.20 (hoping for 1.22 soon) as well as chapel master for:
 - 16-node-XC (aries)
 - 16-node-CS (FDR IB)
 - single node server

The test results are behind our firewall, so for now I think we can just rely on us alerting you about failures. I don't expect there to be many failures given the current CI testing, but if this becomes a problem, we can look at ways of opening up the Arkouda test results.

**Comment by hokiegeek2** [comment]
@ronawho are we good to close this issue?

**Comment by ronawho** [comment]
Yeah, the main spirit of this (add enough automated testing we feel good about upgrading chapel versions) is done. The one thing left in here that I think is still worthwhile is creating more complex benchmarks that are representative of real workflows. I've split that off to https://github.com/mhmerrill/arkouda/issues/399, and will close this.
