### ISSUE TITLE
Include error class name in error messages

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#316]
When the main server loop catches an error that is not a sublcass of `ErrorWithMsg`, it sends a generic error message over the socket, which is not very helpful to the user. Is there a way to print the class name of the error and send a response like "Error: <class UndefinedSymbolError>" or something? Not sure if this works:
```chpl
try {
    // main server select statement
} catch e {
    repMsg = "Error: %s".format(e.type:string);
}
```

Alternatively, we could go through the arkouda source code and make all custom error classes subclass `ErrorWithMsg` and set their own name as part of the message.

**Comment by mhmerrill** [comment]
@bradcray Maybe someone on the chapel team could point us to a solution? Is there a way to use the Reflection module to do this???

**Comment by bradcray** [comment]
I'm not sure reflection can help here because it tends to provide access to information known at compile-time ("What fields are in this record?"  "If I were to make this call, can the compiler resolve it?"), whereas in this case, I'm guessing it's the dynamic type of the class that you want to reason about.

In Chapel 1.21 and on master, all errors now store strings, but I'm not familiar enough with that effort to know what to suggest here (e.g., maybe the default value of that message will help?).  Tagging @dlongnecke-cray, @ben-albrecht, and @mppf who probably have a better grasp on the current status than I do.

**Comment by mhmerrill** [comment]
I think I am going to just fix the exceptions in the arkouda server code making them all subclass the `ErrorWithMsg` class

**Comment by dlongnecke-cray** [comment]
That seems like the best approach to me, for the time being. I can't think of a particular way to circumvent it.

**Comment by ben-albrecht** [comment]
> I'm guessing it's the dynamic type of the class that you want to reason about.

I wonder if this is a reasonable feature request for the long-term.

**Comment by bradcray** [comment]
> I wonder if this is a reasonable feature request for the long-term.

I'm not sure what's being requested here.  It can't be for the compiler to reason about the class's dynamic type (because the compiler can only reason about static information).

**Comment by ben-albrecht** [comment]
I was thinking a function to return the dynamic type of a class at runtime (as a string?). 

That said, embedding the error type in the default message is another reasonable feature request - then you could query off of `e.message()`.

**Comment by mppf** [comment]
The internal function `chpl_error_type_name` uses some compiler primitive magic to get the class name. It seems that we could make a similar function available in Reflection - it's mainly a matter of settling on function names & API description.

**Comment by mhmerrill** [comment]
@hokiegeek2 #412 might be redundant with this issue.

**Comment by hokiegeek2** [comment]
@reuster986 I don't have the class name, but I do have the module name:

![image](https://user-images.githubusercontent.com/10785153/95362343-f4814e00-089b-11eb-8ae9-6e755823d7a7.png)

When I write out e vs e.message(), the class name is included:

![image](https://user-images.githubusercontent.com/10785153/95362472-21356580-089c-11eb-973c-2e2cc609bc18.png)

I'm gonna see if I can include the error class name in the message() output.

This work is in my [fork](https://github.com/hokiegeek2/arkouda/tree/446_enable_rethrowing_of_errors_and_passing_in_strings_to_errors)

**Comment by reuster986** [comment]
@hokiegeek2 great work so far! I commented on the draft PR, but given that there's no easy way to get the class name, I think it's ok to just make sure we replace our custom error classes with `ErrorWithContext` that have a detailed message.

**Comment by bradcray** [comment]
Hi @reuster986 and @hokiegeek2: I may be misunderstanding this issue in some way, but I think @mppf's comment above was right on the mark, though it does rely on non-user-facing features.  I think it would be very reasonable to request that an official user-facing interface for this capability on Chapel's GitHub issues page.

Specifically, note that if you don't catch a Chapel error, you get a message that mentions its (dynamic) name, like:

```
uncaught MyError: 
```

The following internal routine is the one that will convert an Error subclass into a string containing the subclass name:

```chapel
proc chpl_error_type_name(err: borrowed Error) : string {
```

Does that get you where you want to be?

**Comment by hokiegeek2** [comment]
Hi @bradcray I think we got it solved. We basically want to have this level of detail in all error messages:

![image](https://user-images.githubusercontent.com/10785153/95485256-7a1a0200-095f-11eb-90ef-b1863b7840a3.png)

I have this working in my fork.

--John

**Comment by bradcray** [comment]
OK.  It was Bill's "given that there's no easy way to get the class name" comment that caused me to chime in.

**Comment by hokiegeek2** [comment]
@bradcray Gotcha, cool, and thank you for chiming in! The mo' brains the better.

**Comment by hokiegeek2** [comment]
@reuster986 Please confirm if #513 fulfills this requirement.

**Comment by reuster986** [comment]
@hokiegeek2 Confirmed!
