### ISSUE TITLE
write pdarrrayIO unit test cases

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#328]
1. write or leverage existing logic to generate a randomized test hdf5 file that has four columns: str, int, int, float
2. add logic to pytest.ini file to generate the hdf5 file at the start of test harness or unit test execution, and delete the file at the end of test harness or unit test execution.
3. write pdarrrayIO unit tests

**Comment by hokiegeek2** [comment]
Submitted [pull request](https://github.com/mhmerrill/arkouda/pull/383)

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 are we good to close this issue?

**Comment by mhmerrill** [comment]
I am good with closing this now, if wee need to we can open a new issue in the future.
