### ISSUE TITLE
Eliminate copies from ak.arange(), etc.

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#33]
Current pattern (see, for example, [MsgProcessing.chpl](https://github.com/mhmerrill/arkouda/blob/master/MsgProcessing.chpl) in `proc arange`):

```chapel
var aD = makeDistDom(len);
var a = makeDistArray(len, int);
forall i in aD {
    a[i] = i;
}
st.addEntry(new shared SymEntry(a));
```

This creates the SymEntry by copying `a`, in order to avoid accessing the SymEntry within the forall, which hotspots on the class instance.
However, I think we can avoid the hotspotting with a task-private alias. Would the following work?

```chapel
var e = new shared SymEntry(len, int);
forall i in e.aD {
    var a = e.a;
    a[i] = i;
}
st.addEntry(e);
```

**Comment by mhmerrill** [comment]
I think I have now removes all the easy cases of making extra array copies. with PR #195
