### ISSUE TITLE
Rename coargsort to lexsort?

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#332]
I'm not positive that the semantics are the same, but numpy has a [lexsort](https://docs.scipy.org/doc/numpy/reference/generated/numpy.lexsort.html) function that looks very similar to coargsort. If they are the same, it may be worthwhile to change names for symmetry with numpy.

I have no personal preference or stake in this, I just stumbled across lexsort when I was looking to see if there's any clever optimizations we could borrow for coargsort and figured it'd be worth mentioning.

**Comment by reuster986** [comment]
Thanks for bringing it up. It looks like `lexsort` is the opposite-endian version of `coargsort`, i.e. `lexsort` treats the last array in the argument list as the most significant key, wherease `coargsort` treats the first array as the most significant key. Given the semantic difference, I'm inclined to keep the name `coargsort` around, but maybe we could add a `lexsort` function that just calls `coargsort` on the reversed list of arrays? This way, Numpy users expecting a `lexsort` will find it, but arkouda users can keep using `coargsort` in the way that they know.

**Comment by ronawho** [comment]
Gotcha, thanks. I'm going to close this since the semantics are different.
