### ISSUE TITLE
Make arkouda testing dummy-proof (considering myself a dummy)

### ISSUE THREAD

**Issue by bradcray** [mhmerrill/arkouda#337]
While working on Arkouda, I often find myself wishing for more of a "1-button" way to sanity check that I haven't broken anything.  My typical process has (naively) been to run `check.py`, and if that passes, to consider things good.  But that requires manually looking to see that each line says "passed" and as PR #334 taught me, it doesn't cover all the (important) code paths.  I'd hoped that the github checks would be a bit more bullet-proof, but a few bugs I'd introduced slipped by them as well.

For that reason, this issue asks for a way for a naive Arkouda developer to make sure they haven't broken any (key) functionality, ideally with a single line to check for "everything passed"/"nothing failed" rather than having to scan output for distinct "passed" lines or "lack of failure" lines.  As an example, Chapel testing prints out a summary line like:

```
[Summary: #Successes = 0 | #Failures = 1 | #Futures = 0 | #Warnings = 0 ]
```

which can then motivate looking through the more detailed logs to see where the failure took place.

This request is somewhat related to #313.

**Comment by reuster986** [comment]
I agree this would be really helpful. Last week, @mhmerrill , @hokiegeek2 , and I had a conversation about the overhauling arkouda tests. I believe one of the outcomes of that conversation is that @hokiegeek2 plans to separate tests into true integration tests that run automatically in github and exercise major categories of functionality (e.g. `check.py`, `string_test.py`, and `groupby_test.py`) and in-depth unit tests that aim for total coverage (e.g. `operator_tests.py`). 

@hokiegeek2 , to address the points raised in this issue, we should make sure that:

* Integration tests return an exitcode (0 for success, non-zero for failure)
* `make check` calls all available integration tests, checks return codes, and prints a summary line like the above

**Comment by hokiegeek2** [comment]
@reuster986 Cool, will make it happen.

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 @bradcray The [test harness](https://github.com/mhmerrill/arkouda/pull/360) pull request that @mhmerrill just merged in does the following:

1. provides pytest functionality to run all unit Python tests at once. if there are any failures, they are listed.
2. integrates python unit test execution into the Makefile within the make test goal so that all Chapel and Python unit tests as well as integration tests can be executed. if there are any failures, execution of make test goal is suspended and the corresponding errors are listed.
3. enables testing of Python API against local or remote arkouda_server instances. Again, any test failures are listed.
4. returns a 0 exit code if the pytest Python test harness succeeds, allowing the make test goal to continue or a 1 exit code if any of the tests fail, which will case the make test goal to stop.
5. since the pytest-based Python unit test harness is integrated into the Makefile test goal, it can be called from the CI/CD github workflow.

The listed functionality I believe addresses the spirit of the requirements specified by @mhmerrill, @reuster986  and @bradcray, albeit in a slightly different way.  Please let me know if the functionality added in the Python unit test harness [pull request](https://github.com/mhmerrill/arkouda/pull/360) meets the requirements of #313 and #337.

Thanks

--John

**Comment by bradcray** [comment]
This sounds like what I was looking for, thanks!  I'll try to give it a try before too much time passes.

**Comment by bradcray** [comment]
@hokiegeek2: How long do you find it takes to run a `make test` typically?  Mine's been silently on the: `tests/client_test.py` step for quite some time now (1/2 hour?) making me wonder if it's hung up.  (I'm testing against Chapel 1.22 which I don't expect to work, so maybe it's hung up in some way and not making progress?  I'll also try against Chapel 1.20 to see if I get better results).

**Comment by hokiegeek2** [comment]
@bradcray the Python tests portion of make test typically run < 15 seconds. Looks like the client_test cannot connect to an arkouda_server.

**Comment by hokiegeek2** [comment]
the default settings in pytest.ini are as follows:

![image](https://user-images.githubusercontent.com/10785153/81333586-d5735b80-9072-11ea-93b3-889201024058.png)

Are you running in client or full-stack mode?

**Comment by bradcray** [comment]
I'm just running on my laptop (so probably client mode?  I'm not certain ).  Let me try backing out to 1.20 and see if I get better behavior before worrying about the Chapel 1.22 behavior too much (I didn't expect it to pass, but was hoping to see fireworks).

**Comment by hokiegeek2** [comment]
@bradcray should be in full stack mode then if you've not updated the pytest.ini file which is in the arkouda project root directory. This means for each test class (e.g., client_test ), pytest will start up arkouda_server, run the tests, and then shut down the arkouda_server.

To run the python test harness, you run the test harness like this from the project root directory:

`pytest -c pytest.ini`

**Comment by mhmerrill** [comment]
when I do `make test` it does not start the server on my mac... it just hangs
it also hangs when I run `pytest -c pytest.ini` from the command line...
I did need to install `pytest` using `pip3 install pytest`

**Comment by ronawho** [comment]
I think you didn't get pytest-env, which means the env section in the pytest.ini file that tells it to use fullstack mode is ignored. Could do `python3 -m pip install .[test]` or `python3 -m pip install pytest-env`

**Comment by bradcray** [comment]
Elliot's comment was the problem for me.  Once I did `python3 -m pip install .[test]`, things stopped getting stuck.

**Comment by hokiegeek2** [comment]
Cool, thanks @ronawho!

**Comment by mhmerrill** [comment]
@hokiegeek2 I would like this added to the `README.md`

**Comment by bradcray** [comment]
In the spirit of dummy-proof", is there a way to make the Python tests aware of whether or not pytest-env is available, and to print an error if it is not rather than hanging trying to connect to the server?

**Comment by hokiegeek2** [comment]
@mhmerrill on it now. @bradcray I will check on that.

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 @bradcray @ronawho Added unit test guidance to all three README files and submitted a [pull request](https://github.com/mhmerrill/arkouda/pull/368)

**Comment by hokiegeek2** [comment]
@bradcray I can add a pip check to see if pytest-env is installed. The other thing I can do is leverage the client timeout that @ronawho added to throw an error after 30 seconds. Actually both would be good, IMHO. @mhmerrill @reuster986 @ronawho what do you guys think?

**Comment by bradcray** [comment]
I'll defer to others, but these seem good to me.  Specifically, I'm sufficiently python-dumb that if the script said to me "Hey, you didn't install pytest-env and should execute a command like this `blah blah blah` to do so" that would be really helpful.  And the timeout seems like a nice backstop should anything else go wrong if that's easy enough to do.

**Comment by hokiegeek2** [comment]
@bradcray Cool, gotcha, I can add these two features without too much trouble. Also, I did add to the main README the requirement to install pytest and pytest-env, a write-up on the Python and Chapel unit tests, and finally links to the Python and Chapel test README files, so *hopefully* it will be much more apparent to the developer how to run the unit tests.

**Comment by hokiegeek2** [comment]
@bradcray I am testing a [branch](https://github.com/hokiegeek2/arkouda/tree/337_make_arkouda_testing_dummy-proof) now (ported to Chapel 1.22 and working through a make file issue) where I added a client timeout to the arkouda client as well as a check within the base_test.py script where I confirm pytest and pytest_env are installed. These two checks together ensure you won't have the client hanging indefinitely or have a test hang indefinitely due to required libs missing.

**Comment by bradcray** [comment]
Sounds good, thanks!

**Comment by hokiegeek2** [comment]
@bradcray BTW, the name of this ticket cracks me up every time I open it up to add comments.

**Comment by hokiegeek2** [comment]
@bradcray just submitted a pull request for this.

**Comment by hokiegeek2** [comment]
@bradcray my [pull request](https://github.com/mhmerrill/arkouda/pull/377) Please check out the changes I've made and lemme know if the features I've added have satisfied your requirements for this ticket.

**Comment by bradcray** [comment]
Hi @hokiegeek2 — When I run `make test`, I currently see:

```
python3 -m pytest -c pytest.ini
============================= test session starts ==============================
platform darwin -- Python 3.6.0, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/bradc/arkouda, inifile: pytest.ini, testpaths: tests/client_test.py, tests/coargsort_test.py, tests/compare_test.py, tests/dtypes_tests.py, tests/groupby_test.py, tests/join_test.py, tests/operator_tests.py, tests/setops_test.py, tests/where_test.py
plugins: env-0.6.2
collected 48 items                                                             

tests/client_test.py ....                                                [  8%]
tests/coargsort_test.py ....                                             [ 16%]
tests/compare_test.py ...............                                    [ 47%]
tests/dtypes_tests.py ...                                                [ 54%]
tests/groupby_test.py ..                                                 [ 58%]
tests/join_test.py ......                                                [ 70%]
tests/operator_tests.py .........                                        [ 89%]
tests/setops_test.py ....                                                [ 97%]
tests/where_test.py .                                                    [100%]

=============================== warnings summary ===============================
/Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/matplotlib/externals/six.py:80
  /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/matplotlib/externals/six.py:80: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    __import__(name)

/Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/testing.py:22
  /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/testing.py:22: DeprecationWarning: Importing from numpy.testing.decorators is deprecated since numpy 1.15.0, import from numpy.testing instead.
    from numpy.testing.decorators import slow     # noqa

/Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/nosetester.py:13
  /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/nosetester.py:13: DeprecationWarning: Importing from numpy.testing.nosetester is deprecated since 1.15.0, import from numpy.testing instead.
    from numpy.testing import nosetester

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================= 48 passed, 3 warnings in 21.72s ========================
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/SipHashSpeedTest.chpl -o test-bin/SipHashSpeedTest
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/StringGatherSpeedTest.chpl -o test-bin/StringGatherSpeedTest
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/TestBase.chpl -o test-bin/TestBase
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestArgSortMsg.chpl -o test-bin/UnitTestArgSortMsg
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestConcatenate.chpl -o test-bin/UnitTestConcatenate
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestFindLocalSegments.chpl -o test-bin/UnitTestFindLocalSegments
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestGroupby.chpl -o test-bin/UnitTestGroupby
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestIn1d.chpl -o test-bin/UnitTestIn1d
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestLocalArgSortMsg.chpl -o test-bin/UnitTestLocalArgSortMsg
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestMerge.chpl -o test-bin/UnitTestMerge
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestPeelStick.chpl -o test-bin/UnitTestPeelStick
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestReadAllHdfMsg.chpl -o test-bin/UnitTestReadAllHdfMsg
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestSipHash.chpl -o test-bin/UnitTestSipHash
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestSort.chpl -o test-bin/UnitTestSort
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestStringType.chpl -o test-bin/UnitTestStringType
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestSubstringSearch.chpl -o test-bin/UnitTestSubstringSearch
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestUnique.chpl -o test-bin/UnitTestUnique
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/akpow.chpl -o test-bin/akpow
chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/efuncTest.chpl -o test-bin/efuncTest
```

As a `make test` user, what should I be expected to do to feel confident that everything worked as expected?  (e.g., scan the entire output for the string "error" and if I don't see one, assume things are good?).  Is there anything more we could print at the end to summarize that everything passed / nothing failed? (if that's actually the case...).  In its current form, it ends up feeling a little vague and inconclusive.

Based on the above output and checking the Makefile quickly, is it the case that the Chapel unit tests are only compiled but not run at present?  (and if so, is this because not all of the unit tests are working correctly/consistently yet?)

**Comment by hokiegeek2** [comment]
@bradcray here's what happens when pytest and/or pytest-env is not installed:

![image](https://user-images.githubusercontent.com/10785153/83318580-168b0580-a204-11ea-9d4e-b23470ff5b6c.png)

**Comment by hokiegeek2** [comment]
> Hi @hokiegeek2 — When I run `make test`, I currently see:
> 
> ```
> python3 -m pytest -c pytest.ini
> ============================= test session starts ==============================
> platform darwin -- Python 3.6.0, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
> rootdir: /Users/bradc/arkouda, inifile: pytest.ini, testpaths: tests/client_test.py, tests/coargsort_test.py, tests/compare_test.py, tests/dtypes_tests.py, tests/groupby_test.py, tests/join_test.py, tests/operator_tests.py, tests/setops_test.py, tests/where_test.py
> plugins: env-0.6.2
> collected 48 items                                                             
> 
> tests/client_test.py ....                                                [  8%]
> tests/coargsort_test.py ....                                             [ 16%]
> tests/compare_test.py ...............                                    [ 47%]
> tests/dtypes_tests.py ...                                                [ 54%]
> tests/groupby_test.py ..                                                 [ 58%]
> tests/join_test.py ......                                                [ 70%]
> tests/operator_tests.py .........                                        [ 89%]
> tests/setops_test.py ....                                                [ 97%]
> tests/where_test.py .                                                    [100%]
> 
> =============================== warnings summary ===============================
> /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/matplotlib/externals/six.py:80
>   /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/matplotlib/externals/six.py:80: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>     __import__(name)
> 
> /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/testing.py:22
>   /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/testing.py:22: DeprecationWarning: Importing from numpy.testing.decorators is deprecated since numpy 1.15.0, import from numpy.testing instead.
>     from numpy.testing.decorators import slow     # noqa
> 
> /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/nosetester.py:13
>   /Users/bradc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/util/nosetester.py:13: DeprecationWarning: Importing from numpy.testing.nosetester is deprecated since 1.15.0, import from numpy.testing instead.
>     from numpy.testing import nosetester
> 
> -- Docs: https://docs.pytest.org/en/latest/warnings.html
> ======================= 48 passed, 3 warnings in 21.72s ========================
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/SipHashSpeedTest.chpl -o test-bin/SipHashSpeedTest
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/StringGatherSpeedTest.chpl -o test-bin/StringGatherSpeedTest
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/TestBase.chpl -o test-bin/TestBase
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestArgSortMsg.chpl -o test-bin/UnitTestArgSortMsg
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestConcatenate.chpl -o test-bin/UnitTestConcatenate
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestFindLocalSegments.chpl -o test-bin/UnitTestFindLocalSegments
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestGroupby.chpl -o test-bin/UnitTestGroupby
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestIn1d.chpl -o test-bin/UnitTestIn1d
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestLocalArgSortMsg.chpl -o test-bin/UnitTestLocalArgSortMsg
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestMerge.chpl -o test-bin/UnitTestMerge
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestPeelStick.chpl -o test-bin/UnitTestPeelStick
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestReadAllHdfMsg.chpl -o test-bin/UnitTestReadAllHdfMsg
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestSipHash.chpl -o test-bin/UnitTestSipHash
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestSort.chpl -o test-bin/UnitTestSort
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestStringType.chpl -o test-bin/UnitTestStringType
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestSubstringSearch.chpl -o test-bin/UnitTestSubstringSearch
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/UnitTestUnique.chpl -o test-bin/UnitTestUnique
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/akpow.chpl -o test-bin/akpow
> chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq -M /Users/bradc/arkouda//src test/efuncTest.chpl -o test-bin/efuncTest
> ```
> 
> As a `make test` user, what should I be expected to do to feel confident that everything worked as expected? (e.g., scan the entire output for the string "error" and if I don't see one, assume things are good?). Is there anything more we could print at the end to summarize that everything passed / nothing failed? (if that's actually the case...). In its current form, it ends up feeling a little vague and inconclusive.
> 
> Based on the above output and checking the Makefile quickly, is it the case that the Chapel unit tests are only compiled but not run at present? (and if so, is this because not all of the unit tests are working correctly/consistently yet?)

@bradcray I believe that output means the tests were run. Whenever the make test runs successfully for me that's what I see. Evidence for that is the error I am seeing below from a fresh arkouda build on one of my linux boxes:

![image](https://user-images.githubusercontent.com/10785153/83325936-422ae180-a23e-11ea-9a4b-de10b4eaadc8.png)

**Comment by ronawho** [comment]
I'm working on a branch that gets the chapel unit tests running under `start_test`, but today they just get compiled.

I think the standalone chapel tests are useful for isolating specific components, but generally speaking I think the python unit tests are far more valuable and should be what `make test` runs.

Left to my own devices I would end up with targets like:

 - `make check` -- just runs check.py as a quick sanity check (what we have today)
 - `make test` -- alias for `test-python`-- run the python unit tests (which will give a clean color coded summary that should be easy to interpret)
 - `make test-chapel` -- run the chapel unit tests under `start_test`
 - `make test-all` -- run `make check test-python test-chapel`

I think the `check` and `test` terminology line up well with what other projects do.

**Comment by bradcray** [comment]
[Oops, @ronawho and I were typing simultaneously]

Hi @hokiegeek2 — That error you're getting indicates that the `chpl` build of the test is failing, not that the run of the test is failing.  It still might be that the tests are being run, but the output doesn't give any indication of it, and checking through the Makefile, I'm not seeing any indication that they're being run after being compiled either.  This may be by design, though... I believe I've heard that they aren't all working/stable currently (and @ronawho's post seems to indicate this).

My main point in [my previous comment](https://github.com/mhmerrill/arkouda/issues/337#issuecomment-636158435), though was that the original hope for this issue was to have some sort of single summary indicating whether the testing that a developer should run when making changes had passed or failed.  So while things have gotten a lot better through your efforts, the output that `make test` currently generates still feels like it requires the developer to read and understand the whole thing to determine whether things are in a good state or not.  So I don't think we should close this issue yet.

**Comment by ronawho** [comment]
@bradcray if you just run `make test-python` (which I'm proposing `make test` would alias) does that fit what you're looking for?

**Comment by bradcray** [comment]
Assuming (1) that I'd see a count of errors in the following line if there were any and (2) it was what the Arkouda dev team wanted me to use to validate changes before opening a PR, then yes.

```
======================= 48 passed, 3 warnings in 19.47s ========================
```

**Comment by ronawho** [comment]
I obviously can't speak to (2), but for (1) it is pretty obvious when an error occurs. Introducing an error in one of the sort tests:

```diff
diff --git a/tests/coargsort_test.py b/tests/coargsort_test.py
index a27d90c..c725982 100755
--- a/tests/coargsort_test.py
+++ b/tests/coargsort_test.py
@@ -15,7 +15,7 @@ def check_int(N):
     n2 = ak.randint(-(2**15), 2**15, N)

     perm = ak.coargsort([a2])
-    assert ak.is_sorted(a2[perm])
+    assert ak.is_sorted(a2)

     perm = ak.coargsort([n2])
     assert ak.is_sorted(n2[perm])
```

![Screen Shot 2020-06-01 at 1 13 00 PM](https://user-images.githubusercontent.com/1588337/83435114-ab128500-a409-11ea-8999-e48dfe72aa42.png)

**Comment by hokiegeek2** [comment]
@bradcray As @ronawho showed, if there are any python test errors, you'll see the number that failed as well as detailed information for each error.

Just to summarize where we are at (I realize there's a lot to digest WRT to this ticket), the configurable client timeout, python check for required test libraries, and integration of python tests into the `make test` Makefile goal together enable the Arkouda developer to know in short order if there is an issue with either (1) running the tests (client timeout and test library check) or (2) any failing tests due to logic issues.

**Comment by bradcray** [comment]
Yep, understood.  For me, I think the big remaining question is "What tests does the Arkouda team expect a developer to run and check before filing a PR?"  (i.e., what's the best practice that an Arkouda developer should follow?).

If the answer is "just the Python tests" as Elliot suggests, then I think we've got what I wanted here, and simply need to let developers know that `make test-python` is expected to pass for any new PR.

If the answer is "the Python tests and the Chapel tests" then I think the Chapel tests need to be run and a summary of failures across both test suites should be printed out so that only one summary line needs to be checked.

**Comment by reuster986** [comment]
I believe Elliot is correct that the python tests are sufficient for an
arkouda developer to know and demonstrate that things are working
correctly. I see the chapel tests more for deep debugging of things like
performance and scaling issues, and as historical artifacts of the process
of prototyping new arkouda capabilities without involving the client. In
that sense, most of the chapel tests are "obsolete", but I still think we
should hang on to them of course because they are a good starting point for
future debugging and/or prototyping.

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 @bradcray We good to close this issue?

**Comment by bradcray** [comment]
I now believe that I (personally) know what to do as a developer for Arkouda testing, but am not convinced other new developers/contributors to the project would be able to figure it out.  Two minor things that I think would improve that situation would be:

* to have `make test` only run the tests that we expect developers to run before filing a PR (namely `test-python` but not `$(TEST_TARGETS)` since those don't get executed, validated, or summarized at present).
* to have the README section about "Testing Arkouda" say something to this effect: "Arkouda developers should ensure that `make test` passes for any new changes that they plan to contribute back to the project."

(alternatively, we could just do the second bullet and have it name `make test-python` as the required step to me, but that seems slightly less attractive to me in that `make test` seems like the more intuitive thing to run).

But I also don't want to tell the Arkouda team how they should manage their project, so am just pointing out what I'd look for as a new developer to the project to figure out how to run testing and make sure I hadn't broken anything.

**Comment by mhmerrill** [comment]
@bradcray I am ok with any and all suggestions and am very thankful that you guys have taken the time to lend your expertise and experience.

**Comment by hokiegeek2** [comment]
@bradcray Gotcha, I can add that verbiage in the second bullet to the [test README](https://github.com/hokiegeek2/arkouda/tree/master/tests). Is there anything else you can think of that's missing from the test README file?

In terms of make test, sounds like that should be overhauled

**Comment by bradcray** [comment]
> Is there anything else you can think of that's missing from the test README file?

That sounds like another can of worms / separate issue.  :)  I didn't review the README from that perspective, I just searched through it for the word "test" to see if it said what I should do as a developer.

> In terms of make test, sounds like that should be overhauled.

I wasn't imagining anything significant here.  If it were me, I'd just change:

```make
test: test-python $(TEST_TARGETS)
```

to:

```make
test: test-python
```

so that `make test` does the simple / recommended thing that self-verifies.  And then add:

```
.PHONY: test-chapel
test-chapel: $(TEST_TARGETS)
```

so that someone who wanted to compile the Chapel unit tests could do so.  Optionally also:

```
.PHONY: test-all
test-all: test-python test-chapel
```

for convenience (though I don't know how often it'd be used).

**Comment by hokiegeek2** [comment]
@bradcray just to confirm, you've seen the [python](https://github.com/hokiegeek2/arkouda/tree/master/tests) and [chapel](https://github.com/hokiegeek2/arkouda/tree/master/test) README files and you're concerned there are still some gaps? If so, please lemme know what's missing from the Python one if you don't mind because I reworked that recently and I *thought* I had that one in pretty good shape, but maybe not. :)

**Comment by ronawho** [comment]
I had similar thoughts to Brad on `make test` and updating docs. I think I started a branch for that a while back, but then forgot about it. Let me see if I can find that

**Comment by mhmerrill** [comment]
I am ok with doing the `make test` change. That is `make test` just runs the `test-python` target. Or am I missing something?

**Comment by ronawho** [comment]
https://github.com/mhmerrill/arkouda/compare/master...ronawho:improve-testing-docs 

I (and I think a lot of devs) are pretty bad at reading documentation thoroughly. I typically just search for a keyword I'm expecting like "test" and just read that section, so I was trying to go for something that helps with that workflow. 

I think that branch does what Brad was suggesting and Mike ok'd, but I'd have to double check. Feel free to take that branch over, or I can try to get to it tomorrow. I think the main thing I wanted to do was look for stale docs (where CONTRIBUTING.md was a notable one, but I wasn't sure if that's still used or if pydoc/contributing.rst is the official contributing doc)

**Comment by ronawho** [comment]
Whoops, missed mikes last comment before posting that. Yeah, I think it's just making it so that `make test` just runs the python tests, and then adding `test-chapel` and `test-all` targets

**Comment by bradcray** [comment]
> just to confirm, you've seen the python and chapel README files and you're concerned there are still some gaps? If so, please lemme know what's missing from the Python one if you don't mind because I reworked that recently and I thought I had that one in pretty good shape, but maybe not. :)

Oh sorry, no, that's not what I was trying to imply.  I thought you were asking whether I thought there were other, general changes that should be made to the top-level README if we were already editing it, and I was just trying to say that I hadn't reviewed the whole file, so would need to put more time into it to answer that question (and don't think it's necessary for this issue).  I think a simple statement like "New code being developed for Arkouda should pass `make test` in order to be considered for inclusion in the project." is all I was looking for for this issue.  Elliot's mention of CONTRIBUTING.md suggests that it'd be a good place to say this as well, though I haven't trained myself to look beyond top-level READMEs for CONTRIBUTING.md yet, so wouldn't have caught it there...

> I (and I think a lot of devs) are pretty bad at reading documentation thoroughly. I typically just search for a keyword I'm expecting like "test" and just read that section

Exactly.  :)

**Comment by hokiegeek2** [comment]
@bradcray @ronawho Master now includes the following make goals:

test
test-python
test-chapel
test-all

where the default test just executes the python tests via test-python and the only time the chapel tests are run is either by themselves via test-chapel or after the python tests via test-all.

Are we good to close this issue?

**Comment by bradcray** [comment]
Yep, sounds good, thank you!
