### ISSUE TITLE
Add type hints to the Arkouda Python API

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#338]
The concept of [type hints](https://docs.python.org/3.7/library/typing.html) were added to Python in version 3.5. Type hints enable specification of types expected in terms of method parameters as well as method returns. Type hints are a great way to prevent runtime errors stemming from the dynamic typed nature of Python which, while great for quick prototypes, can become a source of tricky-to-debug runtime errors stemming from type mismatches in either method parameter or method return objects.

A very important element of type hints is support for Generics, which enables specification of object types contained in collections such as lists, sets, dicts, tuples, etc... For example, List[str] will make it clear that not only is a method expecting a Python list, it's expecting a list of str objects.

Adding type hints will provide two benefits to Arkouda:

1. Developers will be provided guidance regarding method parameter and method return types, and  this guidance will appear in both the source code as well as in the python docs generated by [Sphinx](https://www.sphinx-doc.org/en/master/index.html)

2. Integration of [mypy](http://mypy-lang.org/) will provide static type checking in Arkouda to catch object type mismatches prior to deployment.

**Comment by hokiegeek2** [comment]
Here's a [good discussion](https://realpython.com/python-type-checking/) of static type-checking in Python

**Comment by reuster986** [comment]
I can see this being very helpful, especially for things like
`ak.concatenate` that take lists of `pdarray` or `Strings`.

**Comment by hokiegeek2** [comment]
Development and testing complete, PR merged, issue resolved.
