### ISSUE TITLE
Add mypy static type checker

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#339]
The [mypy](http://mypy-lang.org/) project delivers a static type checking capability that confirms all API calls feature the correct, expected method parameter and return types. Using mypy will enable both dynamic typing in the development phase of new functionality and static typing for code to be deployed, which can help prevent runtime type errors that are sometimes very difficult to debug.

**Comment by mhmerrill** [comment]
@hokiegeek2 would we run this in the CI lint process possibly or maybe that's a stupid question ;-)

**Comment by hokiegeek2** [comment]
That’s actually an excellent question and yes, we could indeed do that.

—John

**Comment by hokiegeek2** [comment]
I have this working, albeit with a few issues I configured mypy to ignore:

![image](https://user-images.githubusercontent.com/10785153/97491542-af9b8500-1938-11eb-83cc-f6ca0e4f4364.png)

The following lines have to be ignored because there is no numpy library stubs or type hints defined (same for numba and dzmq):

![image](https://user-images.githubusercontent.com/10785153/97491740-f1c4c680-1938-11eb-8a99-688c2cc25a32.png)

![image](https://user-images.githubusercontent.com/10785153/97491807-0e60fe80-1939-11eb-8eaf-d0f51130a190.png)

A couple of lines have to be ignored due to circular dependencies (groupby and categorical, pdarraysetops and categorical), and the annotation fix is unavailable until Arkouda upgrades on Python 3.7:

![image](https://user-images.githubusercontent.com/10785153/97492528-0c4b6f80-193a-11eb-8778-b573c04a2e38.png)

Note: lines with methods can be addressed by method-scoping the imports

**Comment by hokiegeek2** [comment]
completed development, merged into master, issue resolved.
