### ISSUE TITLE
Add configurable Arkouda client timeout

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#346]
Currently if there is not an Arkouda server running on host:port specified in the client config, a request hangs for a long time. I recommend adding a configurable timeout which, if exceeded, causes a Python ConnectionError to be thrown.

**Comment by ronawho** [comment]
👍 I've been wanting something like this for automated testing too. In our nightly testing that checks arkouda against chapel-master the server is crashing, but the scripts are then trying to connect to the server to shut it down. They're hanging forever trying to connect to a server that is no longer running.

**Comment by ronawho** [comment]
I've opened a PR for this for automated testing -- https://github.com/mhmerrill/arkouda/pull/349

However, I think a general user-facing timeout would be nicer, and I'd happily switch to using that instead once we have it.

**Comment by hokiegeek2** [comment]
@ronawho I was able to add a client timeout directly to arkouda client and testing looks good. It's in this [branch](https://github.com/hokiegeek2/arkouda/tree/337_make_arkouda_testing_dummy-proof) and the code is [here](https://github.com/hokiegeek2/arkouda/blob/337_make_arkouda_testing_dummy-proof/arkouda/client.py)

**Comment by hokiegeek2** [comment]
The chapel-gasnet CI workflow consistently fails on running make check:

![ci-arkouda_tests_linux-chapel-gasnet-make-check-failure](https://user-images.githubusercontent.com/10785153/82943753-17077000-9f68-11ea-9dd9-e7c38a335735.JPG)

The error message is the same one I see if the client times out. But...the timeout is occurring at 18-20 seconds.

**Comment by hokiegeek2** [comment]
Once I enabled no timeout all CI workflows suceed, submitted pull request

**Comment by hokiegeek2** [comment]
The merge request was pulled in, capability is fully-tested and documented. ticket resolved.
