### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by buddha314** [mhmerrill/arkouda#353]
Checked out from source on Ubuntu as Windows Subsystem for Linux (yes, i am playing with fire here)

Chapel is installed.

````make
Checking for ZMQ

chpl --fast --ccflags="-Wno-incompatible-pointer-types" -smemTrack=true -lhdf5 -lhdf5_hl -lzmq /mnt/c/Users/b/src/arkouda//dep/checkZMQ.chpl -o /mnt/c/Users/b/src/arkouda//dep/check-zmq

/usr/bin/ld: cannot find -lhdf5

/usr/bin/ld: cannot find -lhdf5_hl

collect2: error: ld returned 1 exit status

make[1]: *** [/usr/local/share/chapel/1.23/runtime/etc/Makefile.exe:31: /tmp/chpl-buddha-13678.deleteme/check-zmq.tmp] Error 1
error: compiling generated source

make: *** [Makefile:105: check-zmq] Error 1```

Probably will be solved by [this stackoverflow](https://stackoverflow.com/questions/39805867/usr-bin-ld-cannot-find-lhdf5-hl) but haven't tried yet, putting this here for posterity.

**Comment by ronawho** [comment]
Arkouda requires hdf5 and zeromq. You can run `make install-deps` to build/install them from source. Or you should be able to install through apt like the CI workflow does:

https://github.com/mhmerrill/arkouda/blob/a8298ff2d43eb4b32fd1a463741a1c2347ce4fc4/.github/workflows/CI.yml#L29-L30

**Comment by ronawho** [comment]
Closing, but let me know if you're still having issues.

**Comment by buddha314** [comment]
Thanks, lost track of this, will re-open if it still happens when I try again.
