### ISSUE TITLE
erroneous version warning (?)

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#361]
Hi Everyone,

I may be wrong, but I believe the following version warning is erroneous as the client and server versions seem like they are the same: client (2020.2.4) and server (2020.02.04)

![image](https://user-images.githubusercontent.com/10785153/80366034-92391180-8856-11ea-8d12-09a7de46aef8.png)

**Comment by reuster986** [comment]
You're right -- the version check I put in is just a string comparison, which is bad logic. I/we should make it a datetime or integer comparison.

https://github.com/mhmerrill/arkouda/blob/5d6df2ac972cb44567c52987904651906d2e4473/arkouda/client.py#L94

**Comment by reuster986** [comment]
I believe this has been fixed, because the python client and chapel server now both render the version as a string exactly as it appears in the VERSION file.
