### ISSUE TITLE
Upgrade to Chapel 1.21/1.22

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#363]
I'd recommend upgrading to Chapel 1.21/1.22 since there were a number of bug fixes and performance optimizations. Additionally, if you're willing to drop support for 1.20 and require 1.21, there are some other code cleanups and further optimizations we can make. In particular, we should be able to optimize aggregation further and enable SrcAggregation under ugni once support for 1.20 is dropped.

My personal preference would be to get the full unit testing online, and then upgrade.

Primary optimizations in 1.21 were:
 - Significant improvements to distributed domain/array creation, particularly at scale (benefits most Arkouda ops)
 - Improvements to the fast-follower optimization (benefits Arkouda binary operations)
 - Improvements to on-stmts on InfiniBand systems (benefits Arkouda operations that use aggregation on InfiniBand)
 - There have been other optimizations as well, but those are the most impactful

Some graphs showing performance improvements with 1.21 (from https://github.com/mhmerrill/arkouda/pull/362):

Cray-XC (Aries) graphs:
---
![121-ak-xc-stream-perf](https://user-images.githubusercontent.com/1588337/80396976-7f890180-8883-11ea-8eb0-373839b3e894.png)

![121-ak-xc-argsort-perf](https://user-images.githubusercontent.com/1588337/80396982-80ba2e80-8883-11ea-93f9-2028a1d9b901.png)

Cray-CS (FDR InfiniBand) graphs:
---

![121-ak-cs-stream-perf](https://user-images.githubusercontent.com/1588337/80397003-87e13c80-8883-11ea-996e-636e20404226.png)

![121-ak-cs-argsort-perf](https://user-images.githubusercontent.com/1588337/80397008-89ab0000-8883-11ea-9703-f7db19184b98.png)

**Comment by mhmerrill** [comment]
@ronawho @bradcray @hokiegeek2 @reuster986 do we have everything in place to move to 1.22?
I'd like to a skip 1.21 altogether.

**Comment by ronawho** [comment]
The last thing I'd like to do is get the Chapel unit tests compiling with 1.22. I have a branch that should be ready on Monday.

**Comment by bradcray** [comment]
For most users, I'd recommend going to 1.21 to 1.22, but since we've been working hard to get Arkouda 1.22 compliant, I think skipping straight to 1.22 makes sense.

Once you do and are willing to no longer keep things working with 1.20, let me know and I'll make some code simplifications w.r.t. some of the PRs I made to support compatibility from 1.20 thru 1.22 (I'll still keep it index-neutral, but rewrite to rely more heavily on features introduced in 1.21 and get rid of some ugly workarounds).

**Comment by ronawho** [comment]
https://github.com/mhmerrill/arkouda/pull/370 gets the Chapel unit tests compiling with 1.22
