### ISSUE TITLE
string_test.py periodically fails

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#364]
In test harness [pull request](https://github.com/mhmerrill/arkouda/pull/360), the test

```python
def run_test_index(strings, test_strings, cat):
    # int index
    assert(strings[N//3] == test_strings[N//3])
    assert(cat[N//3] == test_strings[N//3])
    print("int index passed")
```

called from

```python
 def test_index(self):
        run_test_index(self.strings, self.test_strings, self.cat)
```

periodically fails with the following message:

```
=================================================== short test summary info ====================================================
FAILED tests/string_test.py::StringTest::test_index - assert '\\"\\\\@PSTZ 4' == '"\\@PSTZ 4'
================================================= 1 failed, 8 passed in 2.69s ==================================================
```

**Comment by ronawho** [comment]
In my runs, any of the string unit tests can fail sporadically. I wonder if the random string generation is resulting in non-utf8 strings (or non whatever strings numpy/arkouda support)

**Comment by ronawho** [comment]
cc @reuster986 who I think implemented most of the strings functionally

**Comment by mhmerrill** [comment]
@reuster986 can we close this yet?

**Comment by reuster986** [comment]
No, this issue still needs to be worked. I am looking at it right now, trying to figure out the problem.
