### ISSUE TITLE
StringGatherSpeedTest.chpl failing with latest master version on Linux

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#379]
while running make test on a fresh Linux build with Chapel 1.22 I am seeing this error:

![image](https://user-images.githubusercontent.com/10785153/83326093-2ffd7300-a23f-11ea-916e-6c61d4893015.png)

**Comment by ronawho** [comment]
Whoops, should be fixed by https://github.com/mhmerrill/arkouda/pull/381
