### ISSUE TITLE
Document `randint` and other random vector creators

### ISSUE THREAD

**Issue by buddha314** [mhmerrill/arkouda#403]
I'm trying out Arkouda with some [silly stuff](https://github.com/VerdantAI/math-blog/blob/master/Messing_With_Arkouda.ipynb) and I want to be able to create a vector of random normals with a given mu, sigma.  I see that arkouda provides a `randint`, what other random generators are there?

**Comment by mhmerrill** [comment]
@buddha314 I understand your desire for the long term but in the short term I hope this helps you...
we have a few functions for generating random vectors of things and I believe they all have doc strings, here is list of the exported functions from that part of the Arkouda package...
https://github.com/mhmerrill/arkouda/blob/6de62d263e831fb55e6978e89f3e36952e16d2ac/arkouda/pdarraycreation.py#L11-L13
you could type at the python prompt
```python
[>>> import arkouda as ak
[>>> help(ak.standard_normal)
```
```
Help on function standard_normal in module arkouda.pdarraycreation:

standard_normal(size)
    Draw real numbers from the standard normal distribution.
    
    Parameters
    ----------
    size : int
        The number of samples to draw (size of the returned array)
    
    Returns
    -------
    pdarray, float64
        The array of random numbers
    
    See Also
    --------
    randint
    
    Notes
    -----
    For random samples from :math:`N(\mu, \sigma^2)`, use:
    
    ``(sigma * standard_normal(size)) + mu``
(END)
```

**Comment by mhmerrill** [comment]
@buddha314 I just checked the (`make doc`) documentation but some of these functions are not included in the index for some reason but they do have doc strings in the python code ;-)

**Comment by mhmerrill** [comment]
@reuster986 why do only some functions show up in the Arkouda python doc index. Do they have to be manually added?

**Comment by buddha314** [comment]
Quick note when this goes into production.   `Var(aX) = a^2Var(X)`.  So your method above creates a `N(0, sqrt(sigma))` and not `N(0, sigma)` random variable IF I'm getting the computer right.  Thanks so much!

**Comment by mhmerrill** [comment]
> Quick note when this goes into production. `Var(aX) = a^2Var(X)`. So your method above creates a `N(0, sqrt(sigma))` and not `N(0, sigma)` random variable IF I'm getting the computer right. Thanks so much!

maybe the doc string is wrong?  @reuster986 @buddha314

**Comment by reuster986** [comment]
Hmm, I believe multiplying the standard normal variable by `sigma` should result in a variable with variance `sigma^2`, correct? In the docstring, I'm using the convention `N(mean, variance)`, as opposed to `N(mean, standard_deviation)`.

**Comment by mhmerrill** [comment]
@buddha314 I just put the arkouda docs up at this link https://arkouda.readthedocs.io/en/latest/, they are not perfect but you can see what is there.
