### ISSUE TITLE
Refactor arkouda_server 

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#405]
Following a design discussion with @mhmerrill and @reuster986, the following changes will be made to arkouda_server.chpl to simplify the message handling logic:

1. decode each incoming message element once
2. breakout the incoming message into two elements: (1) string binary containing the cmd, username, and token (the latter for when [basic authentication](#60 )) and (2) a payload element that will have be a space-delimited string binary containing the cmd parameters or a bytes object
3. Push the decision and logic to decode the payload into *Msg functions such as segmentedIndexMsg, countReductionMsg, etc...
4. Change *Msg function signature from (reqMsg, st) to (cmd : string, payload : bytes , st : SymTable)

**Comment by mhmerrill** [comment]
I am not sure about 4) in you list, I think I would like all Msg processing routines to have the same function signature and then do decode inside the Msg processing routine... so that means all `payload` arguments are bytes. The rational for this is because we may want to have a function table approach in the future and I wouldn't want to make that harder.

**Comment by hokiegeek2** [comment]
@mhmerrill yes, you are correct! I realized that a few minutes after I got started, :)

**Comment by mhmerrill** [comment]
I also thing this should be a seprate PR from the authentication work you are currently finishing up. Reasoning being that I would like change to be as incremental as is convenient to ease accepting, testing, and possible backing out thing that don't work or were not a good idea after further examination.

**Comment by hokiegeek2** [comment]
@mhmerrill agreed, will be submitted #60 PR later this AM.

**Comment by hokiegeek2** [comment]
work completed, pull request approved and merged.
