### ISSUE TITLE
io_test fails in CI/CD pipeline

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#407]
Need to figure out the installation process needed to fix this error raised in CI/CD pipeline. Disabled io_test.py until I fix this

![image](https://user-images.githubusercontent.com/10785153/86465283-55c6dd80-bcff-11ea-8d8e-3faa1a9dd544.png)

**Comment by hokiegeek2** [comment]
The reason I did not see this in my testing is that Anaconda automatically install h5ls:

![image](https://user-images.githubusercontent.com/10785153/86591361-6f666000-bf5f-11ea-85da-6e71922ffa71.png)

![image](https://user-images.githubusercontent.com/10785153/86591412-8c9b2e80-bf5f-11ea-9876-b3d6e5faaacb.png)

The CI/CD environment does not use anaconda to manage python dependencies, so this is why the error is currently occurring.

**Comment by hokiegeek2** [comment]
Hmmm...actually, as it turns out, h5ls is indeed installed with hdf5 in arkouda:

![image](https://user-images.githubusercontent.com/10785153/86593376-16003000-bf63-11ea-910b-add66eeb3725.png)

**Comment by hokiegeek2** [comment]
Adding $ARKOUDA_HOME/dep/hdf5-install/bin to the $PATH appears to make the io_test.py run correctly as h5ls is found:

![image](https://user-images.githubusercontent.com/10785153/86602619-e7895180-bf70-11ea-87f4-74d11a0f4265.png)

**Comment by hokiegeek2** [comment]
Still getting an error that h5ls cannot be found:

![image](https://user-images.githubusercontent.com/10785153/86603209-b5c4ba80-bf71-11ea-88c4-167ecddc0829.png)

**Comment by hokiegeek2** [comment]
Okay, now I see why:  the installl-hdf5 goal is not being called in the CI/CD workflow:

![image](https://user-images.githubusercontent.com/10785153/86605087-3f758780-bf74-11ea-9fa3-8489b96eced9.png)

**Comment by hokiegeek2** [comment]
Okay, adding the hdfs-tools install fixes the h5ls missing lib issue:

![image](https://user-images.githubusercontent.com/10785153/86609334-d3961d80-bf79-11ea-8403-f0ebb246ac88.png)

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 @ronawho @bradcray to fix this issue, need to do one of two things: (1) add hdfs-tools to the list of dependencies for the two dependency install sections in the [CI yaml](https://github.com/mhmerrill/arkouda/blob/master/.github/workflows/CI.yml) or (2) run the install-hdf5 goal prior to the tests executing

Seems like option 1 may be the best, but either is cool with me.

--John

**Comment by ronawho** [comment]
Option 1 sounds right. The CI installs with apt instead of building from source with `install-hdf5` because apt install is much faster

**Comment by mhmerrill** [comment]
Option 1 sounds ok to me.

**Comment by hokiegeek2** [comment]
@mhmerrill @ronawho Cool, thanks guys! @mhmerrill @reuster986 I recommend @ronawho update the CI yaml to include the hdf5-tools install so that the io_test.py test cases will run.

**Comment by ronawho** [comment]
I am happy to make that change if you want, but feel free to make it yourself if you'd like. I don't need to be a gatekeeper on the CI infrastructure.

**Comment by hokiegeek2** [comment]
Cool, I will make the change/test within my fork and submit the pull request in the AM.

—oohn

**Comment by hokiegeek2** [comment]
Work complete, submitted [pull request](https://github.com/mhmerrill/arkouda/pull/411)

**Comment by hokiegeek2** [comment]
[Pull request](https://github.com/mhmerrill/arkouda/pull/411) testing succeeded and pull request merged, issue resolved.
