### ISSUE TITLE
improve error handling in arkouda_server

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#412]
There are certain uncaught errors that can cause the arkouda_server chpl process to crash. An example is shown below:

![image](https://user-images.githubusercontent.com/10785153/86954579-3c20fe00-c124-11ea-9a28-658e0b3e141f.png)

I recommend revisiting error handling within the arkouda_server module to catch *Msg-level errors and report back to the client as opposed to crashing arkouda-server

**Comment by mhmerrill** [comment]
@hokiegeek2 this appears to be a case where we expect and `int64` but get a `float64` I think this may be a python side error in the construction of the message to the server.

**Comment by hokiegeek2** [comment]
@mhmerrill This is actually from me sending the string 'nan' through client.generic_msg method. I just wanted to see what would happen if a user sent in an arbitrary string. It _seems_ like we should have a try..catch guard to prevent something like this from crashing the arkouda server where a fat-fingered user (like me) dorks up a command string. :)

**Comment by mhmerrill** [comment]
`ak.generic_msg()` is not really supposed to be called by the user and is not exported, although python still lets the all functions be called.

**Comment by hokiegeek2** [comment]
@mhmerrill gotcha, yeah, I was just trying to see if a malformed command is sent by the user would crash the arkouda_server. if you are thinking something like this is really far-fetched, that's cool.

**Comment by hokiegeek2** [comment]
This issue is covered by #446  and #316, both of which have been developed, tested, and merged into the master, so this issue is resolved.
