### ISSUE TITLE
io_test failures on distributed systems

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#437]
I/O tests like io_test.py are writing to /tmp, but /tmp is usually a filesystem that's local to each machine. For clusters and other cases where the client and and server aren't running on the same machine, this creates problems. 

I'd probably just use a subdir of the arkouda directory to ensure the directory is shared between the login and computes notes.

**Comment by ronawho** [comment]
FYI @hokiegeek2 we see this for our nightly Cray CS/XC testing

**Comment by hokiegeek2** [comment]
@ronawho gotcha, okay, the easiest thing to do would be to add an env variable to make the io test directory configurable. I can do that, or if you want to, that's cool also.

**Comment by ronawho** [comment]
If you have time, that'd be great. It'll be a while until I have a chance.

**Comment by hokiegeek2** [comment]
@ronawho cool, I'm on it

**Comment by ronawho** [comment]
Fixed by https://github.com/mhmerrill/arkouda/pull/439 -- thanks @hokiegeek2!
