### ISSUE TITLE
add dtype field to strings array like and pdarray

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#450]
Add a `Strings.dtype` field to the Arkouda strings array/object so that we can test for `dtype` in the same way we do for `pdarray`.

**Comment by mhmerrill** [comment]
I think for now using the `Strings.bytes.dtype`(which is `np.uint8`) is ok, otherwise we may have to invent something.
@hokiegeek2 and @reuster986 what do you think?

**Comment by hokiegeek2** [comment]
@mhmerrill I vote yes, I like the idea of Strings.bytes.dtype = np.uint8. It's already [implemented](https://github.com/mhmerrill/arkouda/commit/4e3e304ec060d30c4ed444216e58c56a4de6fe28) and I am ready to submit the PR for it.

**Comment by reuster986** [comment]
I think `np.str_` would be more in-keeping with numpy. The problem with doing `np.uint8` is that one day we might want to support actual uint8 arrays as first-class objects, and then a dtype of `np.uint8` would be ambiguous.

**Comment by mhmerrill** [comment]
> I think `np.str_` would be more in-keeping with numpy. The problem with doing `np.uint8` is that one day we might want to support actual uint8 arrays as first-class objects, and then a dtype of `np.uint8` would be ambiguous.

hey, whatever works but inventing a new dtype is a bigger problem, we can use `np.str_` as long as people remember it means "optimized" strings in arkouda.

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 just updated

**Comment by reuster986** [comment]
Note: I should have said `np.str`, not `np.str_`. I'm not sure why I messed that up.

My philosophy on dtype has two aspects:
1. The dtype should answer the question, "from the user's perspective, what is the type of an element of this array?"
2. The dtype should also be a callable function that normalizes any valid scalar to the standard format for elements of that array, e.g.

```python
>>> np.str(5)
'5'
>>> np.str('hello')
'hello'
```

This second characteristic is used in arkouda when converting scalar input and output sent/received over the ZMQ socket.

For `ak.Strings`, I would argue that, from the user's perspective, the elements of the array are variable-length strings, not individual bytes. Numpy does not have a variable-length string dtype per se, but `np.str` is a supertype that encompasses all the numpy string sub-types, so I am comfortable considering arkouda's variable-length string a subtype of `np.str`. I also think that `np.str` satisfies the second aspect as a callable function for converting scalars.

@mhmerrill I hear your concern about people getting confused. I certainly think that's an argument for avoiding one of the fully specified numpy string dtypes like `'<U5'`, but my impression is that `np.str` is broad enough as a supertype to encompass what arkouda has.

**Comment by hokiegeek2** [comment]
Fixed in PR [505](https://github.com/mhmerrill/arkouda/pull/505), PR approved and merged into master, issue resolved.
