### ISSUE TITLE
Feature Request: Interface to Cosine Similarity / Similarity

### ISSUE THREAD

**Issue by buddha314** [mhmerrill/arkouda#467]
Perhaps limited by this issue: https://github.com/chapel-lang/chapel/issues/16311 

Scipy has the [cosine similarity / distance](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html).  It would be useful in both dense and sparse matrices.

**Comment by mhmerrill** [comment]
@reuster986 

- what do you think of this request?
- Is this something we want in the server?
- Seems like we may have almost enough functionality to do this on the python side to start with?

**Comment by mhmerrill** [comment]
@buddha314 I know this doesn't answer the mail completely but I just checked in an example of using arkouda to compute cosine similarity like the spicy routine

**Comment by mhmerrill** [comment]
@buddha314 I am currently putting together some notebooks with examples of Arkouda/Pandas/NumPy integration. To that end I started a new repo called [ArkoudaNotebooks](https://github.com/mhmerrill/ArkoudaNotebooks) I would love it if you would comment or put in some issues there about examples you would like to see.
