### ISSUE TITLE
document all arkouda env vars

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#471]
we now have quite a list of env vars for arkouda...
so I thought we should list and describe all arkouda environment variables

**Comment by mhmerrill** [comment]
@ronawho @hokiegeek2 @reuster986 Here is a list I compiled of potential env vars to be documented
checked ones are ones I think are real and to be documented...

env vars I found mention but no code to read from env:
- [x] ARKOUDA_HOME

potential env vars from makefile:
- [ ] ARKOUDA_PROJECT_DIR
- [ ] ARKOUDA_SOURCE_DIR
- [ ] ARKOUDA_MAIN_MODULE
- [ ] ARKOUDA_MAKEFILES
- [x] ARKOUDA_DEVELOPER
- [x] ARKOUDA_QUICK_COMPILE
- [ ] ARKOUDA_ZMQ_PATH
- [ ] ARKOUDA_HDF5_PATH
- [x] ARKOUDA_SKIP_CHECK_DEPS
- [ ] ARKOUDA_HELP_TEXT
- [ ] ARKOUDA_PRINT_PASSES_FILE

potential env var from testing flow:
- [x] ARKOUDA_SERVER_HOST
- [x] ARKOUDA_SERVER_PORT
- [x] ARKOUDA_FULL_STACK_TEST
- [x] ARKOUDA_NUMLOCALES
- [x] ARKOUDA_VERBOSE
- [x] ARKOUDA_CLIENT_TIMEOUT

potential env vars from server source:
- [x] ARKOUDA_SERVER_AGGREGATION_DST_BUFF_SIZE
- [x] ARKOUDA_SERVER_AGGREGATION_SRC_BUFF_SIZE
- [x] ARKOUDA_SERVER_CONNECTION_INFO

potential env vars from python client source:
- [x] ARKOUDA_TUNNEL_SERVER
- [x] ARKOUDA_KEY_FILE
- [x] ARKOUDA_PASSWORD
- [x] ARKOUDA_CLIENT_DIRECTORY

**Comment by ronawho** [comment]
I probably added a fair number of these, but I'm not sure many of the ones I added are really meant to be user-facing. Not to say they shouldn't be documented, but some may be more developer facing than meant for users. I also wonder if env vars are the best approach. It's what I'm used to as a command-line HPC person, but it's not obvious to me if it's what users are used to. https://github.com/mhmerrill/arkouda/issues/384 may be a better alternative to env vars. 


> ARKOUDA_HOME

This is read in util/test/util.py to determine where to find `./arkouda_server`, which is used by the `make check`, `pytest`, and benchmarking infrastructures. If it's not set, we just walk up the current tree. I don't know that I've ever set this, but added it in case you want to use a current benchmarking infrastructure on an older arkouda install (to for example do performance comparisons with old/new versions)


> ARKOUDA_DEVELOPER
> ARKOUDA_QUICK_COMPILE

Probably worth documenting for developers. ARKOUDA_QUICK_COMPILE really speeds up compilation times. ARKOUDA_DEVELOPER was a related effort, but it keeps runtime checks on to help find out-of-bounds or other bugs. I'm not sure ARKOUDA_DEVELOPER is the right term any more though. Maybe it should be something like `ARKOUDA_RUNTIME_CHECKS`


> ARKOUDA_ZMQ_PATH
> ARKOUDA_HDF5_PATH

These are used as a way to specify paths to pre-built hdf5/zmq installs -- https://github.com/mhmerrill/arkouda/pull/336. May be useful for devs/users


> ARKOUDA_SKIP_CHECK_DEPS

Also useful for devs who know they have the deps installed and want to save a little time. We also use this on some internal systems where we can't directly launch so the execution checks would fail.

> ARKOUDA_PRINT_PASSES_FILE

This is really just something for the nightly testing infrastructure. It results in saving the pass timing to a file, but I'm not sure this is useful for developers or users.

> ARKOUDA_SERVER_AGGREGATION_DST_BUFF_SIZE
> ARKOUDA_SERVER_AGGREGATION_SRC_BUFF_SIZE

These are optimizations env vars. I think they could be worth documenting for users, but we probably want some additional text about how to tune/set them. Ideally I think we'd autotune these at startup, but maybe until we have that it's worth documenting. 

> ARKOUDA_NUMLOCALES
> ARKOUDA_CLIENT_TIMEOUT

These are also used by testing/benchmarking infrastructure

> ARKOUDA_SERVER_CONNECTION_INFO

This was mainly meant for the testing infrastructure, but I also use it when I want to run manually so I don't have to copy+paste the host+port -- https://github.com/mhmerrill/arkouda/pull/243

> ARKOUDA_TUNNEL_SERVER

We use this to build on an XC elogin node, but proxy/tunnel through the login node. Could be useful for devs and users --https://github.com/mhmerrill/arkouda/pull/344

**Comment by mhmerrill** [comment]
@glitch should we make this a markdown file linked off of the readme?

**Comment by glitch** [comment]
> 
> 
> @glitch should we make this a markdown file linked off of the readme?

Looking at the number of them I think a separate file is probably a good idea.  If we wanted to merge it back into the main readme in the future it would be pretty easy and could be encapsulated in an accordion `<details></details>`  element to minimize its visual real estate.

**Comment by mhmerrill** [comment]
@glitch I am closing this for now
