### ISSUE TITLE
pdarrays still allowing iteration in some cases

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#486]
I believe we decided awhile back that pdarrays should never allow iteration and tried to disable it. Users should not be able to accidentally iterate over a pdarray, but they still can, which effectively kills the arkouda_server for large arrays.

Here is a code pattern that activates iteration:
```python
A = ak.arange(10)
B = ak.arange(10)
for a, b in zip(A, B):
    print(a+b)
```

I feel like we really want iterating over a pdarray to raise an exception. I propose the following:
```python
class pdarray:
...
    def __iter__(self):
        raise NotImplementedError
```

**Comment by hokiegeek2** [comment]
@reuster986 Strings as well?

**Comment by hokiegeek2** [comment]
Implemented fix for both pdarrays and Strings:

![image](https://user-images.githubusercontent.com/10785153/94426005-eaa07200-015a-11eb-9d19-005596816705.png)

**Comment by hokiegeek2** [comment]
work complete, PR approved and merged.
