### ISSUE TITLE
Fix ak.array to accept string columns from a Pandas dataframe directly

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#500]
I could not pass an all strings column from a Pandas dataframe directly into `ak.array()` with out exception. below is the current workaround of my function that transfers dataframe columns into the arkouda server. The workaround turns the column into a python `list()` and then passes that to `ak.array()`.

To be clear, the column and the dataframe was constructed from `pd.read_csv()`.

Maybe there is a better way?

```python
# check all objects in iterable for instance of str
# this is a crutch to get a pandas column of str into Arkouda
def is_all_str(a):
    ret = True
    for v in a:
        if isinstance(v, str):
            ret = True
        else:
            ret = False
            break
    return ret

# put data frame columns into arkouda server and return a dict of the pdarrays
# convert some columns into data types the server can understand
def ak_create_akdict_from_df(df):
    akdict = {}
    for cname in df.keys():
        a = df[cname].values
            
        # int64, float64, and np.bool should go over fine
        if a.dtype in [np.int64, np.float64, np.bool]:
            akdict[cname] = ak.array(a)
            print(cname, " : ", a.dtype, "->", a.dtype)
        # time needs to be converted to int64
        elif a.dtype in ["datetime64[ns]"]:
            akdict[cname] = ak.array(a.astype(np.int64))
            print(cname, " : ", a.dtype, "->", akdict[cname].dtype)
        # convert to arkouda Strings object if whole column is instance of str
        elif is_all_str(a):
            # convert to python list of str then ak.array can convert to ak.Strings object
            akdict[cname] = ak.array(list(a))
            print(cname, " : ", a.dtype, "->", 'ak.Strings')
        # something I don't understand how to convert to a server data type
        else:
            print("don't know how to convert ", a.dtype, " !!!")
    return akdict
```

**Comment by hokiegeek2** [comment]
@mhmerrill I was able to go from df string column -> Arkouda Strings as follows:

![image](https://user-images.githubusercontent.com/10785153/99733902-e411e500-2a8f-11eb-9f3d-d1d888949c70.png)

An example of getting to the numpy str array from a dataframe generated from a csv file is as follows:

![image](https://user-images.githubusercontent.com/10785153/99734037-25a29000-2a90-11eb-9a0f-4c4f7d9fee5c.png)

Please let me know if this is what you're looking for.

**Comment by hokiegeek2** [comment]
implemented solution, added unit tests, merged into master, issue resolved.
