### ISSUE TITLE
Enable read/write of bool arrays

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#515]
Currently, when the user tries to `.save()` a bool pdarray, it crashes the server :(  I have never tried to read a bool array, but that might also result in a crash. I think this functionality should be pretty straightforward to add to `GenSymIO.chpl`, but I have been wrong about that before...

**Comment by hokiegeek2** [comment]
@reuster986 Looks like a dtype-related error:

![image](https://user-images.githubusercontent.com/10785153/95464324-ca856580-0947-11eb-9760-5f2fb37af5d8.png)

It looks like there's some hooks in GenSymIO to deliver this functionality:

![image](https://user-images.githubusercontent.com/10785153/95464415-eb4dbb00-0947-11eb-99dc-d8257382f0a6.png)

**Comment by hokiegeek2** [comment]
So the code is within the Chapel HDF5 module, which ultimately would require a Chapel patch:

![image](https://user-images.githubusercontent.com/10785153/95465580-5350d100-0949-11eb-9874-b031a3989410.png)

Not sure if we can add bool HDF5 write support in Arkouda: as booleans appear to be handledd [differently](https://support.hdfgroup.org/HDF5/doc/H5.user/Datatypes.html) than the other Chapel datatypes:

![image](https://user-images.githubusercontent.com/10785153/95466955-e8a09500-094a-11eb-8937-2846c9227f4f.png)

**Comment by reuster986** [comment]
Ouch, yeah, this is bigger than I thought. Definitely worth asking the Chapel team what type to use for bool, and how they want to handle a patch. Whoever writes the patch, I would strongly recommend changing that `halt` to a `throw`.

**Comment by hokiegeek2** [comment]
@reuster986 Agreed, we should just throw an error. I can cook up a quick patch to head off this halt statement if you like.

**Comment by mhmerrill** [comment]
This should still be straight forward. You could convert from chapel `bool` to unit8 then write it as long as you could tag it in the file as a `bool` array/dataset. Chapel `bool` is implementation defined based on the target system.

**Comment by hokiegeek2** [comment]
I updated the code as follows:

![image](https://user-images.githubusercontent.com/10785153/95477208-17703880-0956-11eb-81e1-8847e55733b1.png)

The save "works", but saves as a int64:
![image](https://user-images.githubusercontent.com/10785153/95477113-fc9dc400-0955-11eb-98ec-279a577852cc.png)

**Comment by hokiegeek2** [comment]
@mhmerrill Agreed, we could put some file metadata in there.

**Comment by hokiegeek2** [comment]
Also, looks like some people recommend H5T_BITFIELD for storing booleans. I am trying this out now as it may obviate the need for metadata

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 Okay, from the get_dataset_info I can get the H5T_NATIVE_HBOOL datatype, which is unique obviously, which will enable me to write code that assign 0 to False, 1 to True, and generate the boolean array on read, working this now.

**Comment by reuster986** [comment]
Nice!

**Comment by hokiegeek2** [comment]
Development complete, PR merged into master, issue resolved.
