### ISSUE TITLE
ak.uniform raises TypeError

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#524]
Following the example in the online docs raises a TypeError:

![image](https://user-images.githubusercontent.com/10785153/96183039-51b47980-0f04-11eb-9485-fb12b7e8d33f.png)

**Comment by hokiegeek2** [comment]
Fixed it:

![image](https://user-images.githubusercontent.com/10785153/96184434-7a3d7300-0f06-11eb-9249-3c5c71f66c93.png)

The low parameter was not specified in the delegation call to randint:

![image](https://user-images.githubusercontent.com/10785153/96184595-b07af280-0f06-11eb-92dc-55f8da8ef990.png)

And the parameters were not passed in order, so Python thought it was getting two instances of low:

![image](https://user-images.githubusercontent.com/10785153/96184717-dc967380-0f06-11eb-8123-b5be4e28cb8e.png)

This bug fix took exactly 4 minutes from start to finish -> yay!

**Comment by hokiegeek2** [comment]
Also going to add pdarraycreation test cases.

**Comment by mhmerrill** [comment]
this is clones by #525
