### ISSUE TITLE
Incorrect bandwidth estimation for sorting

### ISSUE THREAD

**Issue by ogreen** [mhmerrill/arkouda#531]
Arkouda is not reporting the correct bandwidth number for the sorting benchmarks. See:

1. https://github.com/mhmerrill/arkouda/issues/41 (#41)
2. https://github.com/mhmerrill/arkouda/blob/master/benchmarks/argsort.py#L30 

There are several important constants missing in the nominator
2* - in each iteration of the sorting algorithm there is a read and a write. By not having the 2* in your equation, you are missing half of the read/writes (and writes are more expensive).
2* - your sorting algorithm does a key-value sort. Meaning it sorts the keys and moves an associated value with that key. Arkouda is only reporting the format size of the “keys” and not for the “values”.
4x or log(size) iterations – the two most popular parallel sorting algorithms are Radix-Sort and Merge-Sort. Radix sort will require 4 iterations for a 16-bit radix to sort the numbers and merge-sort requires log(n) iterations to complete the sort. 
For an array with 128M elements that is 27 iterations. In MergeSort there are several iterations that can be made to be cache efficient. Nonetheless, your bandwidth numbers under-estimate the true amount of bandwidth used.
Therefore, the bandwidth that you are reporting should be around `2*2*4=16x` or `2*2*27=108x` higher.
For Radix-sort you will probably want to report (assuming a Radix of 16 is used):
`bytes_per_sec = (2*4*a.size * (a.itemsize + index_size)) / tavg`
For Merge-Sort you will probably want to report:
`bytes_per_sec = (2**log(a.size)*a.size * a.(a.itemsize + index_size)) / tavg`

(CCing @awthomp )

**Comment by mhmerrill** [comment]
@ogreen @awthomp  I don't think we are incorrect, we just have a different point of view on this topic.

The reported number is intentional in that we
 - only care about the **final sort rate** and not all the data being transferred to get the data sorted.
 - want to be **algorithm agnostic** and don't care which algorithm is being used
 - only care about **sort(keys) -> permutation** because it is what we use, we permute multiple columns based on the **permutation**
 - reporting something more complex doesn't help our users expectation of sort performance
 - there is no standard way of reporting sort performance

I'd be happy to engage in this topic further.

**Comment by ogreen** [comment]
Thanks @mhmerrill . That makes sense.
Just a thought for what could be that the metric of interest: "keys/second" or M keys/second. It's a great throughput metric for sort-performance and will allow easy cross-platform comparison. All you have to do is just get rid of the itemsize factor. But then you need a different throughput metric in your performance table.

**Comment by mhmerrill** [comment]
> Thanks @mhmerrill . That makes sense.
> Just a thought for what could be that the metric of interest: "keys/second" or M keys/second. It's a great throughput metric for sort-performance and will allow easy cross-platform comparison. All you have to do is just get rid of the itemsize factor. But then you need a different throughput metric in your performance table.

@ogreen I see your point.
I will think on this, we currently have different length of keys we care about (mostly 32-bit, sometimes 16-bit and 64-bit).

**Comment by mhmerrill** [comment]
@ogreen @awthomp how deep is your interest in Arkouda? should we setup a call to talk about directions and stuff? do either one of you want to be invited to be a collaborator, means you can help vet PRs and stuff?

**Comment by awthomp** [comment]
> @ogreen @awthomp how deep is your interest in Arkouda? should we setup a call to talk about directions and stuff? do either one of you want to be invited to be a collaborator, means you can help vet PRs and stuff?

@mhmerrill -- let's certainly setup a call to talk about directions and intersection points. We'll get a handful of other NVIDIANs involved as well. CC: @datametrician. I think one of the key actions would be to identify areas of mutual GPU/Arkouda interest and better understanding the long term goals of this library.
