### ISSUE TITLE
uncaught exception in SegmentedMsg.chpl

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#537]
while working on the registration feature I ran into a server crash because of an uncaught undefined symbol exception:
```
subcmd: intIndex objtype: str rest: id_1 id_2 0
uncaught ErrorWithMsg: 
  /home/mhmerri/arkouda//src/MultiTypeSymbolTable.chpl:171: thrown here
  /home/mhmerri/arkouda//src/SegmentedMsg.chpl:248: uncaught here
```
https://github.com/mhmerrill/arkouda/blob/b22487bcd9205419ae8016062757e6fad91ab947/src/SegmentedMsg.chpl#L248

https://github.com/mhmerrill/arkouda/blob/b22487bcd9205419ae8016062757e6fad91ab947/src/SegmentedArray.chpl#L73-L87

https://github.com/mhmerrill/arkouda/blob/b22487bcd9205419ae8016062757e6fad91ab947/src/MultiTypeSymbolTable.chpl#L171

**Comment by mhmerrill** [comment]
if we want to keep the code like this then we might need to implement a throwing check to see if a symbol is in the table. something like lookup but returns nothing or throws on an undefined symbol.
https://github.com/mhmerrill/arkouda/blob/b22487bcd9205419ae8016062757e6fad91ab947/src/MultiTypeSymbolTable.chpl#L167-L177

**Comment by mhmerrill** [comment]
I think I am going to call it `st.checkName(name)`
```chapel
proc checkName(name: string): throws { 
     if (!tab.contains(name)) 
     { 
         if (v) {writeln("undefined symbol ",name);try! stdout.flush();} 
         throw new owned ErrorWithMsg(unknownSymbolError("", name)); 
     } 
 } 
```

**Comment by hokiegeek2** [comment]
@mhmerrill looks good to me. You can integrate the ErrorWithContext object so that the full error context is logged

**Comment by mhmerrill** [comment]
@reuster986 maybe this is what you were complaining about to me the other day.

**Comment by mhmerrill** [comment]
hopefully this is the end of this issue ;-)
