### ISSUE TITLE
string ends-with test intermittently failing

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#549]
I saw a CI test failure checking in a PR #546 which looked like the string ends-with test was failing. I thought this test was decorated with a test-skip but it still looked like a failure.

FYI, since PR #546 did not change this code I went ahead and accepted it.

**Comment by ronawho** [comment]
We have seen this fail in our nightly testing sporadically as well. 

It looks like the skip was added to `run_test_ends_with` instead of `test_ends_with` (so I think it's not actually skipped under pytest)

**Comment by hokiegeek2** [comment]
Looks like test_index is failing on MacOS:

![image](https://user-images.githubusercontent.com/10785153/97420233-71bf4200-18e1-11eb-945b-ca728a20ae27.png)

**Comment by mhmerrill** [comment]
PR #550 skips some string tests

**Comment by mhmerrill** [comment]
@reuster986 @hokiegeek2 do we understand if the skipped string tests are still failing or have been fixed?

**Comment by hokiegeek2** [comment]
@mhmerrill I have not checked them, but I can take a look if you'd like me to

**Comment by hokiegeek2** [comment]
Tested, pushed all changes to git, merted into master, issue resolved.
