### ISSUE TITLE
Recommend upgrading to Python 3.7

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#552]
There are [several improvements](https://docs.python.org/3/whatsnew/3.7.html) in Python 3.7 we can leverage on Arkouda, most notably better type support including [futures typing](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep563) support that fixes the issue of type hints in instance methods such as that shown below:

![image](https://user-images.githubusercontent.com/10785153/97430150-d6cd6480-18ee-11eb-8c3b-8ff58d88ce17.png)

**Comment by mhmerrill** [comment]
@hokiegeek2 Is this just a change to the README.md and setup.py ?

**Comment by hokiegeek2** [comment]
@mhmerrill indeed! 💯

**Comment by hokiegeek2** [comment]
Upgraded, tested, merged in PR, issue resolved
