### ISSUE TITLE
pip install Arkouda fails in virtualenv

### ISSUE THREAD

**Issue by buddha314** [mhmerrill/arkouda#555]
Using WSL + Ubuntu.  Chapel is successfully installed and Arkouda is working at the system level.

To isolate dependencies, I tried to install Arkouda in a virtual environment

```
> python3 -m venv env
> source /env/bin/activate
> pip install arkouda
```

Results in
```
pip install arkouda
Collecting arkouda
  Using cached arkouda-2020.7.7.tar.gz (10.7 MB)
Collecting numpy
  Using cached numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Processing /home/buddha/.cache/pip/wheels/ea/fc/e8/09bb6b4ac8aa0df5f0b402df540308fada9be0b6f056a9c19a/zmq-0.0.0-py3-none-any.whl
Collecting pyzmq
  Using cached pyzmq-19.0.2-cp38-cp38-manylinux1_x86_64.whl (1.1 MB)
Building wheels for collected packages: arkouda
  Building wheel for arkouda (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/buddha/tmp/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ieakr3ov/arkouda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ieakr3ov/arkouda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rwiot76m
       cwd: /tmp/pip-install-ieakr3ov/arkouda/
  Complete output (8 lines):
  /home/buddha/tmp/env/lib/python3.8/site-packages/setuptools/dist.py:473: UserWarning: Normalizing '2020.07.07' to '2020.7.7'
    warnings.warn(
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for arkouda
  Running setup.py clean for arkouda
Failed to build arkouda
Installing collected packages: numpy, pyzmq, zmq, arkouda
    Running setup.py install for arkouda ... error
    ERROR: Command errored out with exit status 1:
     command: /home/buddha/tmp/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ieakr3ov/arkouda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ieakr3ov/arkouda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sv6g_omh/install-record.txt --single-version-externally-managed --compile --install-headers /home/buddha/tmp/env/include/site/python3.8/arkouda
         cwd: /tmp/pip-install-ieakr3ov/arkouda/
    Complete output (46 lines):
    /home/buddha/tmp/env/lib/python3.8/site-packages/setuptools/dist.py:473: UserWarning: Normalizing '2020.07.07' to '2020.7.7'
      warnings.warn(
    running install
    running build
    running build_py
    Existing Chapel install detected
    Installing Arkouda server...
    /usr/bin/ld: cannot find -lhdf5
    /usr/bin/ld: cannot find -lhdf5_hl
    collect2: error: ld returned 1 exit status
    make[1]: *** [/home/buddha/src/chapel/runtime/etc/Makefile.exe:31: /tmp/chpl-buddha-2124.deleteme/check-zmq.tmp] Error 1
    error: compiling generated source
    make: *** [Makefile:109: check-zmq] Error 1

    Exception raised in the process of building Arkouda
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ieakr3ov/arkouda/setup.py", line 20, in <module>
        setup(
      File "/home/buddha/tmp/env/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/buddha/tmp/env/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-ieakr3ov/arkouda/installers.py", line 62, in custom_run
        make_arkouda_server()
      File "/tmp/pip-install-ieakr3ov/arkouda/installers.py", line 32, in make_arkouda_server
        raise ArkoudaBuildError("Error building Arkouda")
    installers.ArkoudaBuildError: Error building Arkouda
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/buddha/tmp/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ieakr3ov/arkouda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ieakr3ov/arkouda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sv6g_omh/install-record.txt --single-version-externally-managed --compile --install-headers /home/buddha/tmp/env/include/site/python3.8/arkouda Check the logs for full command output.
```

One guess was that the `setup.py` provided by Arkouda may have missed some dependencies.  So I ran `pip freeze` on both the system and `env` levels.  Note they are different because we have many different system level requirements.  Here are the outputs

```
(system)
argon2-cffi==20.1.0
-e git+https://github.com/mhmerrill/arkouda.git@847e16b9248df686fb723a6bc8706ef0d6363a35#egg=arkouda
async-generator==1.10
attrs==19.3.0
Automat==0.8.0
backcall==0.2.0
bleach==3.2.1
blinker==1.4
certifi==2019.11.28
cffi==1.14.3
chardet==3.0.4
Click==7.0
cloud-init==20.3
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
dbus-python==1.2.16
decorator==4.4.2
defusedxml==0.6.0
distro==1.4.0
distro-info===0.23ubuntu1
entrypoints==0.3
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
iniconfig==1.1.1
ipykernel==5.3.4
ipython==7.18.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.2
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyterlab-pygments==0.1.2
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
MarkupSafe==1.1.0
mistune==0.8.4
more-itertools==4.2.0
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.2
netifaces==0.10.4
notebook==6.1.4
numpy==1.19.4
oauthlib==3.1.0
packaging==20.4
pandas==1.1.4
pandocfilters==1.4.3
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
prometheus-client==0.8.0
prompt-toolkit==3.0.8
ptyprocess==0.6.0
py==1.9.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.20
Pygments==2.7.2
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.7
pyrsistent==0.15.5
pyserial==3.4
pytest==6.1.2
pytest-env==0.6.2
python-apt==2.0.0+ubuntu0.20.4.1
python-dateutil==2.8.1
python-debian===0.1.36ubuntu1
pytz==2020.4
PyYAML==5.3.1
pyzmq==19.0.2
qtconsole==4.7.7
QtPy==1.9.0
requests==2.22.0
requests-unixsocket==0.2.0
SecretStorage==2.3.1
Send2Trash==1.5.0
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sos==4.0
ssh-import-id==5.10
systemd-python==234
terminado==0.9.1
testpath==0.4.4
toml==0.10.2
tornado==6.0.4
traitlets==5.0.5
Twisted==18.9.0
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
wadllib==1.3.3
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp==1.0.0
zmq==0.0.0
zope.interface==4.7.1
```

```
(env)
numpy==1.19.4
pyzmq==19.0.2
zmq==0.0.0
```

**Comment by buddha314** [comment]
Does the python package need to *install* the arkouda server or just *locate* the arkouda sever?

**Comment by hokiegeek2** [comment]
Odd, worked okay for me:

![image](https://user-images.githubusercontent.com/10785153/98003749-18618200-1dbd-11eb-928f-ea018e69c8cf.png)

**Comment by hokiegeek2** [comment]
@buddha314 Did you try pip install -e .

**Comment by buddha314** [comment]
You're using `pip install -e .` in your `env`? I think that is picking up the requirements already in the arkouda directory.  Can you try it outside of that dir?  Like in a temp directory?

I also found this [stackoverflow](https://stackoverflow.com/questions/21607974/pytables-installation-failed) for PyTables that looks similar.

**Comment by buddha314** [comment]
> 
> 
> @buddha314 Did you try pip install -e .

This runs the `setup.py` in the arkouda directory, which is a nice hint.  I am looking to install in a virtual env for an application outside of arkouda.  If you run in a clean dir, you get 'setup.py not found`

**Comment by mhmerrill** [comment]
@hokiegeek2 @buddha314 oh you might have to install the h5py package and change the Makefile.paths to point to the directory where the library is...
you could also do pip `install -e .[dev]` in the arkouda directory
i really think it is a library path problem and not a python problem

**Comment by mhmerrill** [comment]
> > @buddha314 Did you try pip install -e .
> 
> This runs the `setup.py` in the arkouda directory, which is a nice hint. I am looking to install in a virtual env for an application outside of arkouda. If you run in a clean dir, you get 'setup.py not found`

@buddha314 you could also run `pip3 install -e /path/to/arkouda/repo/[dev]

**Comment by buddha314** [comment]
@mhmerrill I will try that, but it breaks the standard `pip` pattern of trying to remove local dependencies. Do you think the deps could be moved into the pip package?

**Comment by mhmerrill** [comment]
> @mhmerrill I will try that, but it breaks the standard `pip` pattern of trying to remove local dependencies. Do you think the deps could be moved into the pip package?

@buddha314 I didn't build the pip package, @reuster986 did, maybe he has something to contribute to this discussion.

**Comment by buddha314** [comment]
Sure!  It just occurred to me that a good pattern is like the client / server separation for Postgres.  You can install the python Postgres client (psycopg2) on a different machine than the server.  It seems the current Arkouda pip package requires you install both client and server on the same machine.  I expect there is a solution, just don't know it yet.  I'm a bit out of my depth on this one.

**Comment by mhmerrill** [comment]
@buddha314 You can install the arkouda python client without building the server, just in case you need to build the server on a different machine. This is the normal usage for us. That is to build the `arkouda_server` for a cluster and then install the client in your python env.

> Sure! It just occurred to me that a good pattern is like the client / server separation for Postgres. You can install the python Postgres client (psycopg2) on a different machine than the server. It seems the current Arkouda pip package requires you install both client and server on the same machine. I expect there is a solution, just don't know it yet. I'm a bit out of my depth on this one.

**Comment by buddha314** [comment]
The pip package fails to install in a virtualenv unless it's in the arkouda source directory on my machine.

**Comment by mhmerrill** [comment]
@buddha314 if you back-off from the pip install of arkouda from the PyPI, you could
- get a copy of the repo from GitHub
- run a normal non-editable pip install from the repo into your python `venv`
  - since you are not developing arkouda source code
  - this would copy the files instead of link them in to your python `venv`
  - `pip3 install /path/to/arkouda/repo/[dev]`
- then compile the arkouda_server or use an already compiled arkouda_server
- then run the server and client and connect them like normal

**Comment by buddha314** [comment]
the command `pip3 install /path/to/arkouda/repo/[dev]` intermingles the server and client packages.  Also, the `pip install` command says it's building arkouda.  Do you think it's possible to install the arkouda client without downloading the arkouda repo?  I mean, not now, but in the future?

**Comment by reuster986** [comment]
Sorry guys, this is also out of my depth. I created the original, bare-bones PyPI package, but then @Spartee took it over and made it much better. 

@buddha314 I understand your desire to pip install the client only without downloading the whole repo, and I do think we should try to figure out a path for that.

**Comment by buddha314** [comment]
I think the first step is disentangling the client needs for the binary from the server needs.  I feel utterly inadequate to do that.

**Comment by Spartee** [comment]
Hey there @mhmerrill @reuster986. this is definitely possible and I am happy to help, but I want to be sure I understand exactly what everyone wants here.

The original problem seems to be that the pip install fails inside of a virtualenv (with enough information about the virtualenv and platform from @buddha314 I can fix this. e.g. pyenv? virtualenv? virtualenvwrapper? pip-env?)

if what you want is basically two separate pip packages than there are two ways of doing that
1. Actually make two pip packages (separate requirements.txt into requirements-server.txt and requirements-client.txt), create new `setup.py` directives, and completely separate them.

or 

2. Do something similar to other python packages like Dask that have directives built into the pip install.

take a look at [Dask install instructions](https://docs.dask.org/en/latest/install.html) (the `complete` vs the specific packages like `dask.array` etc.). And take a look at how Dask implements that in [their setup.py](https://github.com/dask/dask/blob/master/setup.py). we could have three pip downloads 
1. `arkouda[complete]` server and client
2. `arkouda[server]` 
3. `arkouda[client]`

This route would take a bit more time, but I think it would probably be better unless y'all wanted to truly separate the client and server libraries completely.

What do y'all think?

**Comment by buddha314** [comment]
For my purposes, I'd like to be able to do `pip install arkouda` without having to download the arkouda source or build anything.  That is the typical pip pattern.  If means I can handle my entire python installation within the virtualenv.  Packages like `psycopg2` require you have to have some headers installed OR you can download a binary version.

**Comment by mhmerrill** [comment]
@buddha314 we are still wrestling with this issue and are currently thinking we don't have the resources to commit to distributing a binary for the server with the pip install.
