### ISSUE TITLE
setting ak.pdarrayIterThresh has no effect on limiting the values printed

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#562]
This is probably a Python scoping/global variable thing. when you set `ak.pdarrayIterThresh` it does not have an effect only the original default values is used for some reason.

**Comment by hokiegeek2** [comment]
Yep, confirmed with a code example:

![image](https://user-images.githubusercontent.com/10785153/98537681-9f987500-2257-11eb-8cb7-c92766f316dd.png)

![image](https://user-images.githubusercontent.com/10785153/98537714-ac1ccd80-2257-11eb-8999-68941cfd426d.png)

**Comment by hokiegeek2** [comment]
The logic in set_defaults() looks correct to me per Python docs, investigating.

**Comment by hokiegeek2** [comment]
Ah, I see what's going on. Each module has it's own namespace (a good explanation [here](https://stackoverflow.com/questions/423379/using-global-variables-in-a-function)). Explicitly accessing pdarrayIterThresh within the client module yields the expected behavior:

![image](https://user-images.githubusercontent.com/10785153/98540491-0586fb80-225c-11eb-8aec-17e8b5f12255.png)

The recommended pattern is to define a config module where all global variables are stored. Looking to see if we can retain the pattern of accessing global variables via ak.[variable name]

**Comment by hokiegeek2** [comment]
For what I described above, the client.set_defaults() will not work as expected in that the ak.pdarrayIterThreshold is scoped to the current module. 

![image](https://user-images.githubusercontent.com/10785153/98547954-ecd01300-2266-11eb-8237-058445e55d31.png)

The bottom line is that global values are scoped to modules, not across modules.

**Comment by hokiegeek2** [comment]
To ensure the client-based variables behave as expected, any updates to them must be done as follows:

1. Setting individual variables: client.[variable name] = value
2. Resetting client variables to defaults: client.set_defaultsI()

**Comment by mhmerrill** [comment]
@hokiegeek2 what if we created a singleton object with these values in it and initialized it in the `__init_.py` ? instead of accessing the values directly we would have accessors... ?

**Comment by hokiegeek2** [comment]
@mhmerrill we could create a config module, and put the variables in there. Unfortunately with Python, there's no concept of privately-scoped variables that are only accessible via getters.

**Comment by hokiegeek2** [comment]
@mhmerrill 

For methods in modules outside client to pick up runtime changes to client varaibles, we need to either (1) have a singleton object containing config params or (2) we need to import the client variables with fresh import statements where the variables are used. As shown below, if the variables are loaded at the module level when the script is loaded, any updates to the client variables are not picked up:

![image](https://user-images.githubusercontent.com/10785153/98555160-96b39d80-226f-11eb-9a97-ce4ecf2606f9.png)

![image](https://user-images.githubusercontent.com/10785153/98554687-ffe6e100-226e-11eb-804e-4caff382d5ad.png)

To get any variable updates, import the client variable(s):

![image](https://user-images.githubusercontent.com/10785153/98557107-c9f72c00-2271-11eb-9722-45f1488999cd.png)

![image](https://user-images.githubusercontent.com/10785153/98557216-ea26eb00-2271-11eb-92db-f9d6eb093c32.png)

**Comment by hokiegeek2** [comment]
Also fixed maxTransferBytes and verbose. PR submitted and merged into master, issue resolved.

**Comment by hokiegeek2** [comment]
Missed one import update

**Comment by hokiegeek2** [comment]
Merged in last import statement change that was missed originally, issue resolved
