### ISSUE TITLE
Make one more pass on typechecked coverage

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#567]

**Comment by mhmerrill** [comment]
@hokiegeek2 how did you tag this issue in your commit? that's cool and I want to know.

**Comment by hokiegeek2** [comment]
> @hokiegeek2 how did you tag this issue in your commit? that's cool and I want to know.

Just put hashtag followed by issue number.

**Comment by mhmerrill** [comment]
> > @hokiegeek2 how did you tag this issue in your commit? that's cool and I want to know.
> 
> Just put hashtag followed by issue number.

i guess it tracks that your on a fork of my repo?

**Comment by hokiegeek2** [comment]
development complete, PR merged into master, issue resolved
