### ISSUE TITLE
element-wise bool equals not implemented -> should it be?

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#578]
In the course writing a unit test case I discovered that element-wise equals is not implemented for Arkouda boolean arrays:

![image](https://user-images.githubusercontent.com/10785153/99539831-b8520a80-297c-11eb-9b76-6c22233ae537.png)

![image](https://user-images.githubusercontent.com/10785153/99539762-a40e0d80-297c-11eb-93aa-24ca3c871f6c.png)

Question -> should we implement this?

**Comment by mhmerrill** [comment]
@hokiegeek2 you can synthesize the boolean `==` operator and `!=` operator from the logical operations already implemented. Maybe we should put these into the `pdarray` class definition.

```python
a = ak.randint(0,1,10,dtype=ak.bool)
b = ak.randint(0,1,10,dtype=ak.bool)
# ==
truth = (~(a^b)).all()
# !=
truth = (a^b).any()
```

**Comment by hokiegeek2** [comment]
@mhmerrill gotcha, okay, I recommend that we implement whatever is needed so that bool works like the other data types.

**Comment by reuster986** [comment]
I agree we should implement `bool == bool`. I've had several people ask me about it, and although the workaround is simple, it throws people for a loop.
