### ISSUE TITLE
Change tohdf output filenames to preserve array order

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#580]
Currently, `tohdfMsg` (called by `ak.save()` and `ak.save_all()`) outputs one file per locale, with the locale number in the suffix of the filename, e.g. 60 locales would produce files from `<name>_LOCALE0` to `<name>_LOCALE60`. Because the locale number in the suffix is not zero-padded, when the user goes to read in the files with a wildcard expression, they come back out of order, and the resulting arrays are row-permuted versions of the original arrays.

Two fixes here:
1. In Chapel `tohdfMsg` function, we should zero-pad the locale number in the suffix, so that the ordering of the filenames unambiguously matches the ordering of the locales.
2. In Chapel `readhdfMsg`, when the path argument is a wildcard expression, we should explicitly sort the result of the glob, so that we are not relying on the OS ordering.

**Comment by hokiegeek2** [comment]
Updated filename with zero-padding to enable correct sorting for up to 9999 locales:

![image](https://user-images.githubusercontent.com/10785153/99661866-75526e80-2a32-11eb-9dea-ddcea96b842f.png)

![image](https://user-images.githubusercontent.com/10785153/99661962-9dda6880-2a32-11eb-81e4-e71572c6ee0d.png)

![image](https://user-images.githubusercontent.com/10785153/99662000-acc11b00-2a32-11eb-9843-701e900645c9.png)

**Comment by hokiegeek2** [comment]
The zero-padded file names sort correctly with the default chapel sort comparator:

![image](https://user-images.githubusercontent.com/10785153/99674363-f0705080-2a43-11eb-877c-d9a649152afc.png)


![image](https://user-images.githubusercontent.com/10785153/99674240-ccad0a80-2a43-11eb-860f-29e049f6a64e.png)
