### ISSUE TITLE
ak.Strings.__str__ incorrectly quotes output

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#598]
The first three values are have quotes in the correct places but the second three values after the `...` do not, I believe there is an error on line 114 in the following code
https://github.com/mhmerrill/arkouda/blob/89d91313cd0a8ee913498ceb2da47d35359394f4/arkouda/strings.py#L107-L116

output looks like this
`array(['N/A', 'EWR', 'Boro Zone', ... , Yellow Zone, N/A, N/A])}`
instead of like this
`array(['N/A', 'EWR', 'Boro Zone', ... , 'Yellow Zone', 'N/A', 'N/A'])}`

**Comment by hokiegeek2** [comment]
Fixed and merged into master, issue resolved.
