### ISSUE TITLE
Execution slowdown from logging framework in 605

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#614]
Something about the logging framework added in https://github.com/mhmerrill/arkouda/pull/605 is slowing down Arkouda. The actual benchmark timings haven't changed, but our nightly configurations are timing out from slow non-kernel operations.

With https://github.com/mhmerrill/arkouda/commit/27c293b (before #605):

```
time -p ./benchmarks/stream.py localhost 5555 --trials=1

> ...
> Average time = 0.2336 sec
> real 1.65
> ...
```

With https://github.com/mhmerrill/arkouda/commit/c28e953 (after #605):

```
time -p ./benchmarks/stream.py localhost 5555 --trials=1

> ...
> Average time = 0.2202 sec
> real 169.61
> ...
```

i.e. the timed kernel of stream is 0.2 seconds, but total time jumps from ~1.7s -> ~170s

**Comment by ronawho** [comment]
FYI @mhmerrill and @hokiegeek2 I'm looking into this, just wanted to create the issue to log what I find.

**Comment by hokiegeek2** [comment]
@ronawho The logging framework makes three calls to the Chapel Reflection API...maybe that's something we can't do

**Comment by ronawho** [comment]
The reflection (e.g. [getModuleName()](https://chapel-lang.org/docs/modules/standard/Reflection.html#Reflection.getModuleName)) return `param` (compile time) strings, so there shouldn't be any overhead for those calls at runtime.

**Comment by ronawho** [comment]
As a smaller reproducer, I see a slowdown for a simple array creation:

```python
a = ak.zeros(N, dtype=dtype)
```

This was taking ~40 seconds or so. I think this is from trying to covert the result of `st.lookup()` into a string:

https://github.com/mhmerrill/arkouda/blob/e582bd4456dcebcd62e8d1a9735924df07b7e5c7/src/MsgProcessing.chpl#L78-L79

I think that is trying to convert the symbol table entry (and the entire array it contains) into a string, which will be very slow.
