### ISSUE TITLE
Multi-locale prod reduce performance regression 

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#620]
There was a performance regression for prod reduce in nightly multi-locale perf testing:

![image](https://user-images.githubusercontent.com/1588337/104229513-5fea3700-541a-11eb-9b14-d390ee1ae211.png)

Interactive graph [link](https://chapel-lang.org/perf/arkouda/16-node-cs/?startdate=2020/11/14&enddate=2021/01/11&graphs=reduceperformance). The regression started some time after the 18th, but testing was timing out for a while because of https://github.com/mhmerrill/arkouda/issues/614 so it's not immediately obvious what PR introduced the regression.

**Comment by ronawho** [comment]
While the GiB/s regression looks large, the amount of time taken is quite small still. On 16-node-cs:

```
Before regression : 0.0069s
After regression  : 0.0130s
```

**Comment by ronawho** [comment]
This is from https://github.com/mhmerrill/arkouda/pull/616, specifically changing the range of values in the array from `0-N` to `1-N` -- https://github.com/mhmerrill/arkouda/pull/616/files#diff-fbdcd69de0ebdfd79b3745a619024ec30e41f8a265a252cbe32f5e3b7a868bc2R21

The prod reduce code actually has 2 reductions. One that checks for 0's and one that does the prod reduce:

https://github.com/mhmerrill/arkouda/blob/06924fd21e10064f4fcba28c6325a3552ad9968d/src/ReductionMsg.chpl#L65-L72

When the array had values 0-N we'd only do the first && reduce, but now we're doing both, so it makes sense that things are ~2x slower. 

Note that the && reduce was added in f596b7398a3167df79c8383c93c46a1647248ca0

@reuster986 and @mhmerrill it's not obvious to me if that check-for-zeros is required for correctness or was a performance fast-path. If it's for performance, I think we can just remove it. If it's for correctness and we care about getting the performance back I think we can use a manual reduction that does the * reduce and checks for 0's at the same time.

**Comment by reuster986** [comment]
Ah, that makes sense -- thanks for tracking this down. I actually can't remember why we added that check, but if it does affect correctness, the `--correctness-only` test should catch it if we remove it.

**Comment by ronawho** [comment]
Looking a little more, I think a case where it impacts correctness is if you have an array that would otherwise prod-reduce to INF, and you add a 0 to the array. Do you want that to return 0, or NaN, or INF?

e.g. 

```chpl
var A = [INFINITY, 0.0];
writeln(* reduce A);
```

That's `nan` for Chapel's `* reduce`, but the arkouda prod-reduce currently returns 0.0.

**Comment by mhmerrill** [comment]
@ronawho We should follow what ever numpy prod-reduce does.

**Comment by ronawho** [comment]
https://github.com/mhmerrill/arkouda/commit/f596b7398a3167df79c8383c93c46a1647248ca0 intentionally changed the return type of int64.prod to real instead of int, which is different from numpy. Would you want that changed back?

Ignoring that for a second, it looks like numpy must check for zeros:


```python
A = np.arange(1, 10000, 1)
print((np.prod(A), np.prod(A*1.0))) // (0, inf)  (and warns w/ 'RuntimeWarning: overflow encountered in reduce')

A = np.arange(0, 10000, 1)
print((np.prod(A), np.prod(A*1.0))) // (0, 0.0)
```

And the current arkouda behavior:

```python
A = ak.arange(1, 10000, 1)
print((ak.prod(A), ak.prod(A*1.0))) // (inf, inf)

A = ak.arange(0, 10000, 1)
print((ak.prod(A), ak.prod(A*1.0))) // (0.0, nan)
```

So numpy checks for 0's and returns 0 instead of inf. numpy also detects integer overflow and returns 0 for int64, but I don't know if that's reliable or undefined behavior and they just happen to return 0 in this case (in Chapel, integer overflow is UB and illegal)

So I think the questions to be answered are:
 - Do you want a prod-reduce with a 0 to return 0? (I think yes since this matches numpy -- if so we need to update the float behavior and maybe optimize the int case if you want prod to be as fast as the other reductions)
 - Do you want the return type of prod-reduce on int to be int or float? I'm not sure how to implement that efficiently and legally if you want an int return type, but I can look into it

**Comment by ronawho** [comment]
https://github.com/mhmerrill/arkouda/pull/625 is a draft PR that optimizes the int64 case, and adds the 0 checking for the float64 case. That will resolve this regression and make the float64 case match numpy. 

The int64 case returning a float64 is unchanged and different from numpy. I'll leave that up to you for what you want to do there. If you want to return int64 that implementation will require a non-trivial amount of work and I'm not sure how fast it will be. I'm imagining a custom reduction that before each `*` operation checks if overflow will occurs and if so will set an overflow bit and return 0 maybe with a warning. The check for overflow will add some overhead, though I'm not sure how much.

**Comment by ronawho** [comment]
Ah sorry, turns out I was wrong here. Numpy doesn't do anything special to handle the case where an array has a 0, it's just that numpy is serial and Chapel is parallel. So

```python
A = np.arange(0, 10000, 1) * 1.0
print(np.prod(A))                            # 0
```

will always be computing `0.0 * A[i]`, but in Arkouda/Chapel we'll be running in parallel so one task will be doing the large multiplications and get `inf` and then it will merge with the task that got `0`.

numpy will also get nan if you change the order or multiplications


```python
A = np.arange(9999, -1, -1) * 1.0
print(np.prod(A))                            # nan
```

So I'm thinking we just remove the 0 checking, and there may be differences between the results numpy and arkouda gives, but that's just from a different order of operations inherent in the parallelism.

**Comment by reuster986** [comment]
@ronawho Thanks for doing the detailed comparison with numpy. I agree that removing the 0 check is the way to go, and I approved your PR.

For int64 prod returning a float64, I think I'd like to leave the behavior as-is, even though it differs from numpy. My reasoning is that prod will overflow an int64 for all but trivially tiny arrays (fewer than 63 values with magnitude greater than 1) or highly degenerate arrays (almost all ones). Using float64 extends support for prod to much more realistic arrays, while only sacrificing a small amount of precision in a handful of cases.

**Comment by ronawho** [comment]
Sounds good. I agree with your reasoning for returning `float64` for `int64` prod
