### ISSUE TITLE
Typeguard too strict with scalars

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#634]
We want most arkouda functions to accept both python and numpy scalars, but the type checking currently only allows one type in most cases. For example:

```python
a = ak.randint(0, 100, 10)
amax = a.max()
b = ak.arange(amax)
...
TypeError: start,stop,stride must be type int ...
```

Because `a.max()` returns `np.int64`, but `ak.arange()` only accepts python `int`. Several other functions also have this problem.

@hokiegeek2 would you mind looking at this? Is there an elegant way to make all functions accept both python and numpy scalars of the appropriate type?

**Comment by hokiegeek2** [comment]
@reuster986 yes, just need to update the type annotations in method signatures to something like Union[ak.array,np.array]

**Comment by reuster986** [comment]
Is there any way to tell it that `np.int64` is a subtype of `int`, so that we don't have to change everything by hand?

**Comment by hokiegeek2** [comment]
@reuster986 checking now

**Comment by hokiegeek2** [comment]
@reuster986 Does not look like it:

![image](https://user-images.githubusercontent.com/10785153/105220536-dc210080-5b25-11eb-9e52-c7434070d927.png)

Let's discuss.

**Comment by hokiegeek2** [comment]
@reuster986 Making steady progress on this. There is an apparent typeguard limitation that I had to write a workaround for and also seeing this for np support in random_strings_lognormal:

![image](https://user-images.githubusercontent.com/10785153/105402485-7a2fcc00-5bf5-11eb-8dd6-0ddb8305b353.png)

**Comment by hokiegeek2** [comment]
@reuster986 There's another error cropping up in the numeric.where method:

![image](https://user-images.githubusercontent.com/10785153/105405415-22935f80-5bf9-11eb-80ab-bc0b271f7d82.png)

I'll need to research this...

**Comment by hokiegeek2** [comment]
> @reuster986 Making steady progress on this. There is an apparent typeguard limitation that I had to write a workaround for and also seeing this for np support in random_strings_lognormal:
> 
> ![image](https://user-images.githubusercontent.com/10785153/105402485-7a2fcc00-5bf5-11eb-8dd6-0ddb8305b353.png)

I was able to add support for np.int64, working on np.float64

**Comment by hokiegeek2** [comment]
@reuster986 fixed the random_strings_lognormal type checking, moving on to the other one.

**Comment by hokiegeek2** [comment]
All int/np.int64/float/np.float64 type checking cases covered:

![image](https://user-images.githubusercontent.com/10785153/105419372-9be87d80-5c0c-11eb-8d4c-38e0a775e0fb.png)

**Comment by hokiegeek2** [comment]
Work complete and [PR](merged)
