### ISSUE TITLE
Hash performance regression

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#636]
For some reason, the SipHash performance has tanked. On my laptop, hash rates measured with `SipHashSpeedTest` are down about a factor of 1000 from what they were after the work in #266 . I'm not sure when the regression happened because we don't have a benchmark, which is my fault for losing track of the request in #356 . 

Sample runs on my laptop:

```
$ ./SipHashSpeedTest -nl 1 --NINPUTS=100_000
Hashed 100000 blocks (6.0 MB) in 52.89 seconds (0.11 MB/s)

$ ./SipHashSpeedTest -nl 4 --NINPUTS=100_000
Hashed 100000 blocks (6.0 MB) in 35.32 seconds (0.17 MB/s)
```

I think we should be seeing in the range of 100 MB/s, based on the discussion in #266 .

@ronawho do you have time to look at this soon-ish? I will also try to figure out what's going on, but there's a good chance you will see something that I miss.

**Comment by ronawho** [comment]
Yeah I can start looking soon (hopefully later today or tomorrow.) Just to confirm, I also see poor performance today. Running with comm=none on chapcs (same 24-core machine we run nightly comm=none perf testing on):

Today's sha (01/21/21), with Chapel 1.23.0:

```
git checkout fc5fa31
make test-bin/SipHashSpeedTest

./test-bin/SipHashSpeedTest --NINPUTS=100_000
> Hashed 100000 blocks (6.0 MB) in 65.21 seconds (0.09 MB/s)
```

Right after #298 -- includes optimizations motived by #266 and a bug fix for them (02/25/20), with Chapel 1.20.0:

```
git checkout 59da8f0
make test-bin/SipHashSpeedTest

./test-bin/SipHashSpeedTest --NINPUTS=100_000
> Hashed 100000 blocks (800000 bytes) in 0.00 seconds
> Rate = 2784.45 MB/s

./test-bin/SipHashSpeedTest --NINPUTS=1_000_000_000
> Hashed 1000000000 blocks (8000000000 bytes) in 1.40 seconds
> Rate = 5457.36 MB/s

```

**Comment by ronawho** [comment]
This could be partially from https://github.com/mhmerrill/arkouda/pull/605, which had a lot of other regressions. See https://github.com/mhmerrill/arkouda/issues/614 for more info on that. 

Before #605:

```
git checkout 27c293b
make test-bin/SipHashSpeedTest

./test-bin/SipHashSpeedTest --NINPUTS=100_000
> Hashed 100000 blocks (6.0 MB) in 0.00 seconds (17341.04 MB/s)
```

After #605:

```
git checkout c28e953
make test-bin/SipHashSpeedTest

 ./test-bin/SipHashSpeedTest --NINPUTS=100_000
> Hashed 100000 blocks (6.0 MB) in 63.91 seconds (0.09 MB/s)
```

**Comment by ronawho** [comment]
And specifically this seems to be from removing a `param` flag around the `TRACE` function in https://github.com/mhmerrill/arkouda/pull/605/files#diff-3ba7ccd70c846b464e44cf23727f4ef353240a3548632c410bfe810cc8933797L145.

With that param removed, there's now a ton of string creation and concatenation being done as part of the function call to `shLogger.debug()`

**Comment by ronawho** [comment]
Like usual, I failed in my attempt to not look at this immediately :)

Fix should be in https://github.com/mhmerrill/arkouda/pull/637

**Comment by reuster986** [comment]
@ronawho I have always relied on being able to distract you with a good performance issue :) :) Thanks for fixing this!
