### ISSUE TITLE
CI workflow arkouda_python_portability (3.x) job error

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#643]
Just observed the following error in the arkouda_python_portability (3.x) job:

![image](https://user-images.githubusercontent.com/10785153/105991711-25b3a300-6072-11eb-84d5-6843a3badb58.png)

First time that I've seen this, will see if I can reproduce it.

**Comment by ronawho** [comment]
Do you have a link to the failure?

**Comment by hokiegeek2** [comment]
@ronawho Argh, sorry, I re-ran that job to see if I could reproduce it, so far, no. So...this may be a one-off we won't see again.

**Comment by hokiegeek2** [comment]
Only saw this once, think it's unlikely to be a common occurrence
