### ISSUE TITLE
ensure string_test delimiter is not in gremlins array

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#644]
Today I ran into an instance where the string_test self.delim was in the gremlins array (in this case, ' '). Recommend adding recursive helper method to ensure gremlin delimiters are avoided

**Comment by reuster986** [comment]
@hokiegeek2 I would expect `' '` (space) to be a common delimiter. Shouldn't we support it?

**Comment by reuster986** [comment]
Same with `'"'` (double quote), which should be a valid delimiter. But we should throw an error on `''` (empty string), since it makes no sense to split on it or ask whether a string ends with it.

**Comment by hokiegeek2** [comment]
@reuster986 Good points! Yeah, I agree that we should support space and double quote as delimiters. That's something I'll be happy to work on at your's and Mike's direction.

**Comment by hokiegeek2** [comment]
Merged in code changes, issue resolved.
