### ISSUE TITLE
BFS Chapel Algorithm

### ISSUE THREAD

**Issue by zhihuidu** [mhmerrill/arkouda#651]
A graph extension in Arkouda to implement BFS algorithm has been implemented in the reporatory 
https://github.com/Bader-Research/arkouda
the branch graph-functionality is for single locale (the link for BFS algorithm is as follows)
https://github.com/Bader-Research/arkouda/blob/graph-functionality/src/SegmentedMsg.chpl#L1835
and the branch graph-multilocales is for multilocales BFS(please see the link below)
https://github.com/Bader-Research/arkouda/blob/graph-multilocales/src/SegmentedMsg.chpl#L1862

The basic idea of the BFS in Chapel is using FORALL to search the next level vertices and use set to store the new vertices. 
@bradcray would you please check and let me know the possible performance problem of the current two versions of the BFS algorithm in Chapel?  

@mhmerrill Now we can compile and run small data on sherlock. About the large data you mentioned, I am not sure how to read them and build the graph in memory. Currently our BFS algorithm just reads some txt file of edge list to build the graph in memory.

**Comment by mhmerrill** [comment]
@zhihuidu did we address these concerns for you? If so can we close this?

**Comment by zhihuidu** [comment]
Yes, the tests on sherlock have given us the answers. please close this issue. Thanks!
