### ISSUE TITLE
Specific Pandas and Numpy versions needed for datetime functionality

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#656]
One of the datetime_test cases fails:

![image](https://user-images.githubusercontent.com/10785153/106904447-334bd700-66c9-11eb-86ae-cff15e0935fa.png)

In my environment I have pandas 1.0.5. I noticed in the successful [CI pytest workflow](https://github.com/mhmerrill/arkouda/actions/runs/535817165) indicates the pandas version is 1.2.1:

![image](https://user-images.githubusercontent.com/10785153/106904937-c1c05880-66c9-11eb-9ee6-bcbd67c1670c.png)

After upgrading to pandas 1.2.1 and mypy 1.16.5 (pandas 1.2.1 needs >= numpy 1.16.5), all datetime_test cases pass:

![image](https://user-images.githubusercontent.com/10785153/106905554-65116d80-66ca-11eb-8b93-2cdaf1196baa.png)

Ran pytest and all unit tests pass with pandas 1.2.1 and numpy 1.16.5:

![image](https://user-images.githubusercontent.com/10785153/106906031-c5081400-66ca-11eb-98f3-4b674e8cfecc.png)

@mhmerrill @reuster986 Given this issue and [654](https://github.com/mhmerrill/arkouda/issues/654), I recommend we update setup.py to specify numpy and pandas versions.

**Comment by hokiegeek2** [comment]
Looks like we can go with Pandas 1.1.0 as the minimum Pandas version and 1.16.5 as the minimum Numpy version:

![image](https://user-images.githubusercontent.com/10785153/106907322-1ebd0e00-66cc-11eb-9b7a-3a9ba7e5b792.png)

**Comment by hokiegeek2** [comment]
Also fixes #654

**Comment by hokiegeek2** [comment]
Confirmed fix for #654:

![image](https://user-images.githubusercontent.com/10785153/106924955-9e070d80-66dd-11eb-9f54-e76628fbd6fb.png)

**Comment by reuster986** [comment]
@hokiegeek2 @mhmerrill I can confirm arkouda works in our internal environment with numpy==1.19 and pandas==1.1. I think we are good to require the minimum versions you suggested. Do we also need to specify numpy<1.20 because of the mypy issue?

**Comment by reuster986** [comment]
Sorry, just saw the PR where you did exactly that. Please disregard!

**Comment by hokiegeek2** [comment]
merged in [PR](https://github.com/mhmerrill/arkouda/pull/657), issue resolved
