### ISSUE TITLE
String sort performance seems low

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#659]
There are new string benchmarks for groupby, gather, argsort, and coargsort. groupy and gather performance isn't terrible, but argsort looks pretty bad. From today's [16-node-cs-hdr](https://chapel-lang.org/perf/arkouda/16-node-cs-hdr/?startdate=2021/02/04&enddate=2021/02/06&graphs=argsortperformance,coargsortperformance,groupbyperformance,gatherperformance,stringargsortperformance,stringcoargsortperformance,stringgroupbyperformance,stringgatherperformance) runs:

| benchmark       | numeric     | string      |
| --------------- | ----------: | ----------: |
| 2-arr goupby    |  1.49 GiB/s | 0.122 GiB/s |
| gather          | 43.85 GiB/s | 4.310 GiB/s |
| argsort         |  4.69 GiB/s | 0.002 GiB/s |
| 2-arr coargsort |  2.35 GiB/s | 0.005 GiB/s |

So string goupby/gather are ~10x slower, but string sorting is ~2000x slower.

**Comment by hokiegeek2** [comment]
@ronawho is this with the latest from master?

**Comment by ronawho** [comment]
Yeah, this is from the nightly runs.

**Comment by reuster986** [comment]
Yeah, that does seem fishy. I would expect string sorting to be slower than string groupby (because the former operates on the actual, variable-length strings while the latter uses fixed-length hashes), but a net 200x is quite striking.

Also, it is a bit surprising that strings are 10x slower than ints for groupby/gather. I would have expected about 3-4x, but I don't have an easy way to test on infiniband.

Alas, nothing comes readily to mind as a culprit for these issues. I mean, other than me :)

**Comment by ronawho** [comment]
> Yeah, that does seem fishy. I would expect string sorting to be slower than string groupby (because the former operates on the actual, variable-length strings while the latter uses fixed-length hashes), but a net 200x is quite striking.

Oh, that's interesting. For some reason I thought string sorting was operating on the hashes too, but I've never looked at this code in detail. I plan on digging into this over the next week or 2. 

This is probably the code I'm remembering (from when I was optimizing numeric coargsort), but it might not be what's actually called:

https://github.com/mhmerrill/arkouda/blob/4a3855fd940160355880a5194736500fb896d982/src/ArgSortMsg.chpl#L432-L445

> Also, it is a bit surprising that strings are 10x slower than ints for groupby/gather. I would have expected about 3-4x, but I don't have an easy way to test on infiniband.

I suspect this is because we're aggregating `uint(8)` compared to `int(64)`. We see similar performance for gathering `bool`. We should be able to improve performance by aggregating the entire string at once instead of individual characters. https://github.com/mhmerrill/arkouda/issues/527#issuecomment-712838097 has more info on this, and I expect to look at that at some point in the near-ish future.

**Comment by ronawho** [comment]
Ah, I see that the `twoPhaseStringSort()` is what's being called to sort. Ironically, `twoPhaseStringSort` seems pretty fast, and it's actually `isSorted()`/`ediff()` that seems to be the bottleneck:

https://github.com/mhmerrill/arkouda/blob/52d639ab899aa48050955e4b1351a6a36d819620/src/SegmentedArray.chpl#L676-L720

I have not dug into `ediff` yet, but I'm guessing a lot of the array accesses are fine-grained and remote. Skipping the `isSorted()` call with `checkSorted=false` I see a ~100x speedup

**Comment by ronawho** [comment]
That helps performance a lot for 16-node-xc, but 16-node-cs-hdr wasn't much better because there was other fine-grained communication. https://github.com/mhmerrill/arkouda/pull/671 should fix that by converting more code to use aggregation.

**Comment by reuster986** [comment]
@ronawho good catch, and thanks for fixing these issues! 

Looking back at `ediff`, it is somewhat reminiscent of the bitwise reductions we were just working on. Makes me wonder if we can use a similar custom `ReduceScanOp` to solve this problem. Perhaps I will look into that next.

**Comment by ronawho** [comment]
>> Yeah, that does seem fishy. I would expect string sorting to be slower than string groupby (because the former operates on the actual, variable-length strings while the latter uses fixed-length hashes), but a net 200x is quite striking.

> Oh, that's interesting. For some reason I thought string sorting was operating on the hashes too, but I've never looked at this code in detail. I plan on digging into this over the next week or 2.

It looks like plain argsort operates on the raw variable-length strings, but coargsort operations on the hashes. I opened https://github.com/mhmerrill/arkouda/issues/677 to explore this.

**Comment by ronawho** [comment]
coargsort performance actually isn't bad since it's operating on the hash. I just set the problem size too low to start and there's a fixed overhead that makes performance look low. https://github.com/mhmerrill/arkouda/pull/676 increases the problem size and the rates for the benchmarks look better (though I expect there's lot of room for improvement yet.)

**Comment by ronawho** [comment]
Here's the current [16-node-cs-hdr](https://chapel-lang.org/perf/arkouda/16-node-cs-hdr/?startdate=2021/02/05&enddate=2021/02/19&graphs=argsortperformance,coargsortperformance,groupbyperformance,gatherperformance,stringargsortperformance,stringcoargsortperformance,stringgroupbyperformance,stringgatherperformance) results:

| benchmark       | numeric     | string     |
| --------------- | ----------: | ---------: |
| 2-arr goupby    |  1.49 GiB/s | 0.57 GiB/s |
| gather          | 43.85 GiB/s | 8.75 GiB/s |
| argsort         |  4.69 GiB/s | 0.66 GiB/s |
| 2-arr coargsort |  2.35 GiB/s | 0.51 GiB/s |

So str groupby within 3x of numeric, str gather within 5x, argsort within 7x, and coargsort within 5x. Still plenty of room for improvement but the core issue of sort performance looking low has been resolved so I'm going to close this.

**Comment by ronawho** [comment]
Current [16-node-cs-hdr](https://chapel-lang.org/perf/arkouda/16-node-cs-hdr/?startdate=2021/04/07&enddate=2021/04/12&configs=nightly&graphs=argsortperformance,coargsortperformance,groupbyperformance,gatherperformance,stringargsortperformance,stringcoargsortperformance,stringgroupbyperformance,stringgatherperformance) results (collecting for something else and figured it's worth updating here):

| benchmark       | numeric      | string      |
| --------------- | -----------: | ----------: |
| 2-arr goupby    |   5.09 GiB/s |  1.26 GiB/s |
| gather          | 118.60 GiB/s | 26.40 GiB/s |
| argsort         |  11.42 GiB/s |  1.83 GiB/s |
| 2-arr coargsort |   8.21 GiB/s |  2.01 GiB/s |

The ratios are about the same with str groupby within 4x of numeric, gather within 5x, argsort within 7x, and coargsort within 5x, but the rates for each are significantly higher than they were before.
