### ISSUE TITLE
change/rename server command line argument --logging to --trace

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#660]
change/rename server command line argument `--logging` to `--trace`, I think we should make this update as part of PR #649

**Comment by mhmerrill** [comment]
@hokiegeek2 @reuster986 I believe we agreed to this already, correct?

**Comment by hokiegeek2** [comment]
@hokiegeek2 👍 from me. :)

**Comment by hokiegeek2** [comment]
Merged [PR](https://github.com/mhmerrill/arkouda/pull/650), issue resolved
