### ISSUE TITLE
Single node str-argsort is slow

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#680]
The chapcs configuration (single node `CHPL_COMM=none`) is timing out on str-argsort with the recent problem size increase. It looks like we optimized multi-locale string sorting, but single locale is still slow. Looking at the breakdown, I see that almost all the time is spent gathering and sorting long strings:

```
make test-bin/StringArgsortSpeedTest
./test-bin/StringArgsortSpeedTest --maxLen=16 --size=$((10**6*2)) --v

> twoPhaseStringSort Line 73 DEBUG [Chapel] Gathered long strings in 4.771183e+00 seconds
> twoPhaseStringSort Line 80 DEBUG [Chapel] Sorted long strings in 2.226543e+01 seconds
> ...
> twoPhaseStringSort Line 93 DEBUG [Chapel] Sorted ranks in 2.614360e-01 seconds
> Sorted 2000000 strings (17.0 MB) in 28.25 seconds (0.60 MB/s)
```

@reuster986 I'm not very familiar with this code yet, but it looks like it takes "long" strings and converts them to chapel strings and then calls the regular chapel sort on them. Do you remember the context/motivation for this?

**Comment by ronawho** [comment]
My guess is that because radix sort has an iteration for each "digit", this was to avoid a long tail of sorting that would only be operating on a few longer strings, but I'm not sure.

**Comment by ronawho** [comment]
Increasing the `SegStringSort.SSS_MINBYTES` to be bigger than maxLen (so skip long string gathering/sorting) performs much better:

```
# slow gathering/sorting long strings
./test-bin/StringArgsortSpeedTest --maxLen=16 --size=$((10**6*2)) --v
> Sorted 2000000 strings (17.0 MB) in 28.25 seconds (0.60 MB/s)

# skip gathering/sorting long strings 
./test-bin/StringArgsortSpeedTest --maxLen=16 --size=$((10**6*2)) --v --SegStringSort.SSS_MINBYTES=18
> Sorted 2000000 strings (17.0 MB) in 0.22 seconds (75.56 MB/s)

# skip gathering/sorting long strings with larger problem size
./test-bin/StringArgsortSpeedTest --maxLen=16 --size=$((10**8)) --v --SegStringSort.SSS_MINBYTES=18
> Sorted 100000000 strings (858.0 MB) in 6.97 seconds (123.17 MB/s)
```

**Comment by reuster986** [comment]
> My guess is that because radix sort has an iteration for each "digit", this was to avoid a long tail of sorting that would only be operating on a few longer strings, but I'm not sure.

@ronawho this is exactly right. I believe in multi-locale tests, doing this proved worthwhile, but that was with my pre-aggregation code, so maybe it is no longer necessary.

**Comment by ronawho** [comment]
I think the concept makes sense still. If you have a couple million 16 byte strings and a handful of 1024 byte strings this seems like it'd be a huge win.

Probably what we need to do is tune the heuristic for what to consider as long and then look at how long strings are gathered/sorted. Converting them to chapel strings and sorting the chapel strings is probably pretty slow.

For now I'm thinking about just disabling the partitioning to start and I'll look at the performance of that later. Thoughts?
