### ISSUE TITLE
Add Datetime/Timedelta identity initializer

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#689]
Currently, calling `ak.Datetime(x)` where `x` is already a `ak.Datetime` raises an error. Instead, `x = ak.Datetime(x)` should be a no-op, from the user's perspective. Same with `ak.Timedelta`.

**Comment by hokiegeek2** [comment]
[PR](https://github.com/mhmerrill/arkouda/pull/698) merged, issue resolved.
