### ISSUE TITLE
Restore support for Categorical == str

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#691]
`ak.Categorical` instances used to support comparisons with `str` scalars, but apparently lost that support when type-checking was added. Specifically `ak.Categorical._binop()` should accept both `Categorical` and string scalars (`str`, `np.str`, `np.str_`, etc.) argument types. The functionality already exists; I think the type-checking is just preventing it from executing. Partly my fault for not putting in a unit test for it.

**Comment by mhmerrill** [comment]
fixed by PR #700
