### ISSUE TITLE
Include docs for Chapel code in Read-the-Docs

### ISSUE THREAD

**Issue by glitch** [mhmerrill/arkouda#693]
Many files in the Chapel code under the `src` directory contain doc strings.  Figure out how to get this included in the auto-generated documentation on arkouda.readthedocs.io under the Chapel API Reference

**Comment by mhmerrill** [comment]
@glitch you can drop something into the chapel gitter channel on this, to see if you can get some help if you need it.

**Comment by glitch** [comment]
@mhmerrill  thanks!

Note: Looking through Chapel's `chpldoc` target they have created a Sphinx extension called the chapel domain library to help generate their Sphinx documentation for Chapel (here: https://pypi.org/project/sphinxcontrib-chapeldomain/ ).

I think it's just a matter of adding it to the extensions and auto_api_dirs in conf.py after getting it installed via pip and making sure sphinx can find the extension.

**Comment by mhmerrill** [comment]
> @mhmerrill thanks!
> 
> Note: Looking through Chapel's `chpldoc` target they have created a Sphinx extension called the chapel domain library to help generate their Sphinx documentation for Chapel (here: https://pypi.org/project/sphinxcontrib-chapeldomain/ ).
> 
> I think it's just a matter of adding it to the extensions and auto_api_dirs in conf.py after getting it installed via pip and making sure sphinx can find the extension.

Are they still using a really old version of Sphinx? like 1.x or something like that?

**Comment by glitch** [comment]
Hmm, I see the issue now.  Chapel's sphinxcontrib-chapeldomain plugin version 0.0.15 (declared in `$CHPL_HOME/third-party/chpl-venv/sphinxcontrib-chapeldomain/sphinxcontrib/chapeldomain/__init__.py`) has sphinx version limits of 1.6.0-1.6.999 declared in `setup.py` but in the `requirements.txt` declares version 1.8.5 which throws an error when trying to build the docs via `make chlpdoc`

I updated the versions in `setup.py` to match that in `requirements.txt` which allows `chpldoc` to get built.  This gets me to the next error over in arkouda where `sphinx_rtd_theme` cannot be found.

The end goal will be to update the sphinx version in chapel-lang and submit a patch to those folks asking them to publish a new version of sphinxcontrib-chapeldomain.  I'm going to target a sphinx version which matches arkouda's and test everything out on the side first.

**Comment by lydia-duncan** [comment]
Hi, we already have an update to our usage of the Sphinx domain and other required packages so that it's compatible with Python 3.  It should be using Sphinx 3.2.1, not 1.8.5, and it shouldn't have the issue with specifying 1.6.0 in some places and 1.8.5 in others.  Are you seeing problems with the latest checkout of master for chpldoc and the latest PyPI release of the Sphinx domain?

**Comment by glitch** [comment]
Hi Lydia,
I was working out of the 1.23.0 release tarball.  Running `make chpldoc` was failing and the issue looked like a Sphinx version mis-match under `third-party/chpl-venv/sphinxcontrib-chapeldomain` where `setup.py` bounds it to 1.6.0-1.6.999 but `requirements.txt` was declaring 1.8.5.  I did notice there was a newer version of the python package in pypi (0.0.19) but hadn't yet checked the latest version of chapel from github.  I'll give the updated package a shot, thanks!

**Comment by glitch** [comment]
Just as follow up:   the PR for this issue is [PR-696](https://github.com/mhmerrill/arkouda/pull/696)

Minor bookeeping:
- I pulled the Chapel 1.23.0 Docker image from docker hub and verified it contains a working `chpldoc` command.
- I re-downloaded the chapel 1.23.0 release from github with sha256:7ae2c8f17a7b98ac68378e94a842cf16d4ab0bcfeabc0fee5ab4aaa07b205661 and running `make all` does not build chpldoc (I probably needed to pass it a flag I missed), running a follow up `make chpldoc` fails with the error 
```
ERROR: Cannot install -r chpldoc-requirements.txt (line 12) and Sphinx==1.8.5 because these package versions have conflicting dependencies.
```
- I tried the same with downloading the release sources for tag 1.23.0 with sha256:9350261afd9421254c516bcdd899ca5a431c011b79893029625c8d70fa157452 and ran into the same issue.
- Chapel master branch has this all fixed so I expect release 1.24.0 cause everything to resume working again

The patches included in the PR fix the versioning issue with Sphinx and allows someone with the Chapel 1.23.0 source or release tarball to build chpldoc (again these will not be needed with 1.24.0 as it looks like the issue has been thoroughly sorted on the chapel-lang/chapel master branch).

Note: I'm not sure what the difference is between the 1.23.0 source and the docker image, but I expect it's all going to be moot.

**Comment by lydia-duncan** [comment]
Thanks for following up on that.  We'll try to be better about jumping on deprecation warnings w.r.t. our release cycle :)

**Comment by glitch** [comment]
Ok, I finally figured out what is going on here; `readthedocs` is actually the cause of the problem.  The Makefile targets are completely fine and work without issue (which is why running locally all of the documentation shows up).  For reference the current documentation build is a two step process:
- `make doc-python` : runs the normal sphinx doc generation process
- `make doc-server` : this runs the `chpldoc` command and copies the generated chapel docs for arkouda into place `docs/server/` where we previously had an index.rst placeholder.

When `readthedocs` publishes your documentation, it does just copy it from the `docs` folder, instead it _checks out your project_ and runs its _own_ sphinx command to rebuild the docs.  This means it completely skips our make doc targets and is the reason why the server docs aren't showing up on `readthedocs`.  Poking around on their builds section an viewing the raw build commands is what finally tipped me off:  https://readthedocs.org/projects/arkouda/builds/13259636/

This means we'll either need to change something in the readthedocs configuration or fully integrate the chpldoc build process in our sphinx doc-gen process.

**Comment by mhmerrill** [comment]
@glitch I am sorry I didn't explain this you you as I push the original Arkouda read-the-docs thing together... You are correct in what you say about this... I was hoping there was a way to run `chpldoc` in the `sphinx` flow.

**Comment by glitch** [comment]
Ok, this is what I was able to figure out :)

ReadtheDocs doesn't want to support custom docker containers which means we can't call `chpldoc` in our readthedocs documentation build.  (This is what we are currently doing in our Makefile, pointing `chpldoc` at arkouda-server.chpl to determine which modules are used to generate the api docs.)

An alternative is to use Github pages.  There is a nice plugin in the marketplace (it's free: https://github.com/marketplace/actions/deploy-to-github-pages ) which handles deploying your docs to Github Pages.  The gist of what happens is this:

- A separate branch in your repo is created named gh-pages
- You add a workflow (generally you set this to only run on pushes to master) which checks out the code, builds the docs and pushes only the contents of that folder to the gh-pages branch.  So gh-pages only contains documentation, no code.
- You configure your github repo pages section (Settings -> scroll down to Github pages) Source to point to the gh-pages branch and /(root).
- Once configured and the workflow run you should have docs located at `<project | user name>.github.io/<repo name>`

Here's an example from my fork
- gh-pages branch which now contains only the docs:   https://github.com/glitch/arkouda/tree/gh-pages
- The documentation lives at : https://glitch.github.io/arkouda/

One downside the docs are not versioned and can't be previewed... although nothing stops you from building them locally.  There are some work-arounds like this (https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/ see part 2 for versioning) which involves wrapping the sphinx command in a bash script to simulate what read the docs is doing.

**Comment by glitch** [comment]
Opened PR707 https://github.com/mhmerrill/arkouda/pull/707

If we go the GitHub pages route, it will obsolete the ReadTheDocs portion, but I left that workflow and README links in place for now.

**Comment by mhmerrill** [comment]
I think this is ok, I did know about this path before read-the-docs and we had a big argument about keeping built docs in the repo... maybe we should have the convo again between the team. I am a little weirded-out by having a branch in the repo like this... ;-)
