### ISSUE TITLE
Authenticate flag throws exception/error

### ISSUE THREAD

**Issue by glitch** [mhmerrill/arkouda#714]
When running the following, an exception/error is thrown, because the string concatenation & formatting is done in the wrong order.

Steps to reproduce, run
```
./arkouda_server -nl 1 --authenticate

uncaught SystemError: Invalid argument: Too many arguments for format string (in string.format)
  /home/foo/projects/arkouda//src/arkouda_server.chpl:92: thrown here
  /home/foo/projects/arkouda//src/arkouda_server.chpl:92: uncaught here
```

The offending line is [here](https://github.com/mhmerrill/arkouda/blob/591d26ea71ee54f3006673c8f5cfcd045b7e0c02/src/arkouda_server.chpl#L91)
```
        serverMessage = ">>>>>>>>>>>>>>> server listening on tcp://%s:%t?token=%s " +
                        "<<<<<<<<<<<<<<<".format(serverHostname, ServerPort, serverToken);
```
The formatting is done on the second string which has no substitution args; those live in the first string.  It looks like it was a simple formatting mistake from commit:300c142417d74e85e95178a9a5bbc3867e39ee47 which added some extra output to that string.

Note: It's a pretty trivial patch, but I want to add a unit test for it.

**Comment by hokiegeek2** [comment]
@glitch Yeesh, good catch. That's my fault. Actually, if you don't mind, please hold off. I updated the startup message to fix the formatting and I'll fold a fix for this into my PR

**Comment by glitch** [comment]
@hokiegeek2 Cool, no problem.

**Comment by glitch** [comment]
This was what I was going to do:
```
serverMessage = ">>>>>>>>>>>>>>> " +
                            "server listening on tcp://%s:%t?token=%s ".format(serverHostname, ServerPort, serverToken) +
                            "<<<<<<<<<<<<<<<";
```
;)

**Comment by hokiegeek2** [comment]
@glitch Yup, that will fix it. What won't get fixed is the crappy formatting I added, LOL. My PR will fix that. 🥇

**Comment by glitch** [comment]
@hokiegeek2 While you're in there, `printServerSpashMessage` is missing an `l`, it should be "Splash".

**Comment by hokiegeek2** [comment]
@glitch Actually, go for it. You found it, you should fix it. It may be my formatting changes will be frowned upon, LOL

**Comment by glitch** [comment]
@hokiegeek2 Ok, will do.  This will actually be a good intro for @pierce314159 and I to work together on making a test.  I'm thinking of testing it through the pytest harness rather than something in Chapel mostly because it's in the `proc main` section.

**Comment by hokiegeek2** [comment]
@glitch good call, agreed.
