### ISSUE TITLE
Categorical.concatenate ordered and interleave features are not working as expected

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#719]
The pydocs state that the default Categorical.concatenate method invocation is sorted, meaning that the 2..n Categorical object elements are to be appended in order:

![image](https://user-images.githubusercontent.com/10785153/112531432-f1ace380-8d7d-11eb-8487-c88a37c3c2fa.png)

This is the case if locales=1. Otherwise, the Categorical object elements are interleaved in no particular order:

![image](https://user-images.githubusercontent.com/10785153/112532223-f0c88180-8d7e-11eb-9f6c-a14e44e1d8bd.png)

**Comment by mhmerrill** [comment]
@reuster986 what do you think about this issue? it is a documentation bug or do we need to change code?

**Comment by reuster986** [comment]
Hmm, at first glance, this is even worse than the issue title suggests. The output ordering is not even interleaved; it's just wrong. Code will need to be changed, but I don't know what yet.

**Comment by reuster986** [comment]
Ok, I'm attempting to reproduce this bug on a build from 02/26, and everything is coming out correct. So I'm wondering if something in the last month broke concatenation... Does concatenation of `ak.Strings` still work correctly?

**Comment by hokiegeek2** [comment]
@reuster986 on it now. the ak.Strings contcatenate tests as written pass...but I am concerned our test coverage didn't catch what you reported. please email me your test case when you get a chance.

**Comment by hokiegeek2** [comment]
@reuster986 I have a [branch](https://github.com/hokiegeek2/arkouda/tree/719_categorical_concatenate_interleaves_arrays_irrespective_of_ordered_boolean) where I revereted [ConcatenateMsg.chpl](https://github.com/hokiegeek2/arkouda/blob/719_categorical_concatenate_interleaves_arrays_irrespective_of_ordered_boolean/src/ConcatenateMsg.chpl) back to the [20210211](https://github.com/hokiegeek2/arkouda/blob/03641b988851e22656b0ea16096c72e8aa07668a/src/ConcatenateMsg.chpl) commit.

On a 3 locale Arkouda instance the ak.concatenate ordered parameter appears to work correctly for pdarray and Strings concatenation:

![image](https://user-images.githubusercontent.com/10785153/113861195-ecd03280-9774-11eb-8684-994da62631cf.png)

![image](https://user-images.githubusercontent.com/10785153/113860448-0f158080-9774-11eb-8fee-3f1bd107c35b.png)

However, neither ak.concatenate ordered nor interleave work correctly for Categorical concatenation:

![image](https://user-images.githubusercontent.com/10785153/113858853-366b4e00-9772-11eb-8b15-e6b70216e8de.png)

From the main [branch](https://github.com/hokiegeek2/arkouda) in my fork, I see similar results where ak.concatenate works correctly for pdarrays and Strings, but incorrectly for Categoricals:

![image](https://user-images.githubusercontent.com/10785153/113866150-f5c40280-977a-11eb-9242-0c38bffcdd53.png)

Consequently, I believe the concatenate interleave and ordering logic does not appear to be working for Categoricals in either the 20210211 and current snapshots

**Comment by reuster986** [comment]
I tested on 10 nodes of our Cray XC, using a build from 2021-02-26. I created two 15-element Categoricals with the same categories and concatenated them using both `ordered=False` and `ordered=True` and got the correct answer both times.

The code does break when the categories are different (raises an AttributeError), but when they are the same, at least the ordering is correct. I don't know what the difference is between your test and mine. I'm also not sure how your test on 20210211 is not raising an error with different categories.

**Comment by hokiegeek2** [comment]
@reuster986 Okay, I will see what I can do about updating the test cases so I can replicate the errors you are seeing. In the meantime, perhaps it makes sense to back out the ConcantenateMsg changes because it appears they are interfering with our users' normal use cases. What do you think?

**Comment by reuster986** [comment]
@hokiegeek2 Yeah, we should definitely get to the bottom of what's going wrong. I'm just very confused.

**Comment by hokiegeek2** [comment]
The results from the [concatenate](https://github.com/hokiegeek2/arkouda/tree/concatenate-improvements) branch from my fork look good for the two Strings objects I concatenated. These are Strings objects each with a length of 10 concatenated on a 3 node cluster:

![image](https://user-images.githubusercontent.com/10785153/114608405-a7779d80-9c6b-11eb-9a4a-cbe79c464066.png)

**Comment by hokiegeek2** [comment]
Concatenation of three Strings objects, one of which has a length matching or one less than the number of locales is working correctly:

![image](https://user-images.githubusercontent.com/10785153/114609512-e35f3280-9c6c-11eb-95c6-49ef4c4cd8af.png)

![image](https://user-images.githubusercontent.com/10785153/114609739-1f929300-9c6d-11eb-9031-b0a845f9c99e.png)

**Comment by hokiegeek2** [comment]
11 locales where all Strings arrays have lengths < numLocales is working correctly:

![image](https://user-images.githubusercontent.com/10785153/114611505-1e626580-9c6f-11eb-928f-ad4bb9bc18a9.png)

**Comment by hokiegeek2** [comment]
My testing with @reuster986 fixes in #758 with different categories on 15 locales with the categorica.testConcatenate in #710 works correctly:

![image](https://user-images.githubusercontent.com/10785153/114888852-977ccc80-9dd7-11eb-9c88-aeaa02cf9e12.png)

My other testing looks good as well. @mhmerrill I believe this can be closed.

**Comment by mhmerrill** [comment]
ok, will close based on your rec @hokiegeek2
