### ISSUE TITLE
Make server-side loggers individually configurable.

### ISSUE THREAD

**Issue by glitch** [mhmerrill/arkouda#728]
Currently the loggers on the arkouda_server are managed with a global configuration variable `v` defined in [ServerConfig](https://github.com/mhmerrill/arkouda/blob/8e4400fd1abb307aacef47f56404d59f3a05f6ff/src/ServerConfig.chpl#L24)

Chapel allows `config const` values to be set via cmd line args such as  `--FooClass.v=true` and we can take advantage of this feature to allow more customized logging configuration.

It may also be worth looking into a common log configuration format to allow groups of modules/classes to be turned on and off at once (i.e. something similar to how logback or log4j work... not the dynamic part, but the config file part).  If we look at the (optional) config file the format should be something like yaml or json, and the order of override should be config file, overridden by command-line args.

**Comment by glitch** [comment]
Associating with Issue #757

**Comment by hokiegeek2** [comment]
Got this working. The default logging level is INFO. The first example is with arkouda_server (notice arkouda_directory debug message):

![image](https://user-images.githubusercontent.com/10785153/114772394-bd549380-9d3b-11eb-9926-411efd8801c6.png)

![image](https://user-images.githubusercontent.com/10785153/114772342-ac0b8700-9d3b-11eb-8a5d-7d5fdabff151.png)

Second one is MsgProcessing debug:

![image](https://user-images.githubusercontent.com/10785153/114772749-2e944680-9d3c-11eb-9806-ffab33111d49.png)

![image](https://user-images.githubusercontent.com/10785153/114772570-f5f46d00-9d3b-11eb-9976-6cc7bc5dbe71.png)

And the third one is MsgProcessing warn:

![image](https://user-images.githubusercontent.com/10785153/114772714-20462a80-9d3c-11eb-8908-afdabb62d848.png)
