### ISSUE TITLE
Create isRegistered function for pdarrayclass/Strings objects

### ISSUE THREAD

**Issue by glitch** [mhmerrill/arkouda#735]
Related to issues #729 and #734 it would be nice to have an `isRegistered` function on the pdarrayclass objects.  More generally all we really need is a function on the client `isRegistered(<name:str>)` which can be used by pdarrayclass, GroupBy, etc.

Server side code to check the internal registry in MultiTypeSymbolTable.SymbolTable  and return simple True/False messages will need to be added as well as all of the plumbing for a new command etc.

Note: We can submit this change with the #729 PR, but as a separate consolidated commit in case we need to unwind/backport/etc. it later.

**Comment by mhmerrill** [comment]
I am ok with this approach.

**Comment by mhmerrill** [comment]
@pierce314159 did we add this functionality? I don't remember seeing it in the PRs.

**Comment by pierce314159** [comment]
@mhmerrill not yet, this is my goal for today. Do we want to stick with adding a new command on the server side approach or would it be better to handle this all on the client side using the list registry functionality of the info command?

**Comment by mhmerrill** [comment]
i think just using the pulling the registered value from `ak.info()` seems like the right way to go since the information is there.

**Comment by mhmerrill** [comment]
@pierce314159 could you also pull the notebook from the notebook repo and add some stuff to it...

https://github.com/mhmerrill/ArkoudaNotebooks/blob/master/RegistrationTest.ipynb

**Comment by pierce314159** [comment]
> 
> 
> @pierce314159 could you also pull the notebook from the notebook repo and add some stuff to it...
> 
> https://github.com/mhmerrill/ArkoudaNotebooks/blob/master/RegistrationTest.ipynb

Can do!

**Comment by pierce314159** [comment]
I'm about to put a pull request for this issue. I added a generic `list_registry` function in addition to class level `is_registered` functions for `Strings` and `pdarrayclass` all of this was done on the client side using the `ak.info("__RegisteredSymbols__")` functionality from issue #734

I did not include `groupby` or `categorical` objects since they don't have `register` functions yet
