### ISSUE TITLE
Should `ak.from_series` perform default conversion on `object`?

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#737]
Currently, calling `ak.from_series(col)` on a pandas `Series` of strings raises an error, i.e. the user is forced to specify an arkouda dtype. This behavior is probably surprising for users, who expect arkouda strings to come from pandas/python strings. 

* Is there a way for `ak.from_series` to detect strings as the dtype and automatically convert to arkouda strings?
* If we can't easily distinguish pandas/python strings from other things with `object` dtype, then should `ak.from_series` try to cast all instances of `object` as strings?

I would vote yes to the latter, but would welcome other perspectives.

**Comment by hokiegeek2** [comment]
@reuster986 gotcha, okay, sounds like a lot of our users use from_series for strings.

I see what you meant. We infer the dtype for int and bool Series but not for str Series:

![image](https://user-images.githubusercontent.com/10785153/114048660-c683c300-9858-11eb-9a4c-5cfc3c9165fe.png)

I would agree that casting as strings as a default makes good sense.

**Comment by hokiegeek2** [comment]
@reuster986 [PR](https://github.com/mhmerrill/arkouda/pull/741) submitted for your review

**Comment by mhmerrill** [comment]
@hokiegeek2 @reuster986 Can we close this now?
