### ISSUE TITLE
Need python3 tests to check arkouda against numpy/pandas

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/arkouda#90]
Enhancements to consider:
 * adding more sanity checks to the `check.py`
 * creating a new randomized test for some feature
 * others kinds... use your imagination ;-)

**Comment by ronawho** [comment]
Anything left to do here, or is this completed with @hokiegeek2 recent work in https://github.com/mhmerrill/arkouda/pull/360?

**Comment by hokiegeek2** [comment]
@mhmerrill do you think we should close this issue?

**Comment by mhmerrill** [comment]
yes we can open a new one in the future if something else is identified.
